/**
 * Customer-facing text. English is the source of truth: TypeScript fails the
 * build if an Amharic string is missing. Have a native speaker review the
 * Amharic before launch. Admin screens are English only.
 */
/**
 * Cart, checkout and payment text. English only for now: the Amharic copy of these screens must be written by a
 * native speaker (a wrong word in a payment instruction costs money), so `am` reuses the English until then.
 */
const CART_STRINGS = {
  'cart.title': 'Cart',
  'cart.empty': 'Your cart is empty',
  'cart.emptyBody': 'Add packs from a game page, then check out here.',
  'cart.browse': 'Browse games',
  'cart.add': 'Add to cart',
  'cart.added': 'Added to cart',
  'cart.remove': 'Remove',
  'cart.qty': 'Quantity',
  'cart.total': 'Total',
  'cart.checkout': 'Check out',
  'cart.unavailable': 'No longer available',
  'cart.unavailableBody': 'Remove it to continue.',
  'cart.fixFirst': 'Fix these first:',
  'cart.problem.fill_fields': 'enter the ID',
  'cart.problem.checking': 'checking the ID…',
  'cart.problem.invalid_id': "the ID isn't valid",
  'cart.problem.check_failed': "couldn't check the ID, tap Retry",
  'cart.problem.check_expired': 'the ID check ran out, check it again',
  'cart.problem.confirm_id': 'tick that you checked the ID',
  'cart.problem.wrong_region': "this pack isn't for that account's region",
  'cart.problem.region_unknown': "the account's region couldn't be confirmed",
  'cart.problem.unavailable': 'no longer available',
  'cart.problem.package_unavailable': 'not available',
  'cart.problem.choose_package': 'not available',
  'cart.dropped': 'These items are no longer for sale and were removed: {items}',
  'cart.fixIds': 'These items need their player ID checked again: {items}',
  'cart.checkoutFailed': "Couldn't start checkout. Check your connection and try again.",
  'cart.loadError': "Couldn't load your cart. Check your connection and try again.",
  'cart.pending': 'You have an order waiting for payment.',
  'pay.title': 'Pay',
  'pay.amount': 'Send exactly',
  'pay.method': 'Pay with',
  'pay.telebirr': 'Telebirr',
  'pay.cbe': 'CBE',
  'pay.sendTo': 'Send to',
  'pay.accountName': 'Account name',
  'pay.accountNumber': 'Account number',
  'pay.noAccount': 'This payment method is not available yet. Try the other one, or contact support.',
  'pay.steps.telebirr': 'Send the amount above by Telebirr to this number, then enter the transaction number from your receipt below.',
  'pay.steps.cbe': 'Send the amount above to this CBE account, then enter the transaction ID from your receipt below (it starts with FT).',
  'pay.ref.telebirr': 'Telebirr transaction number',
  'pay.ref.cbe': 'CBE transaction ID',
  'pay.refHint.telebirr': 'Find it in your Telebirr receipt or SMS.',
  'pay.refHint.cbe': 'Find it on your CBE receipt or SMS. It starts with FT.',
  'pay.refRequired': 'Enter the reference from your payment receipt.',
  'pay.submit': 'Verify payment',
  'pay.verifying': 'Checking your payment…',
  'pay.wait': 'Still checking. This can take a moment.',
  'pay.paidTitle': 'Payment confirmed',
  'pay.paidBody': 'We received {amount}. Thank you.',
  'pay.mismatchTitle': "We're reviewing your payment",
  'pay.mismatchBody': "We found your transfer, but its amount doesn't match this order ({amount}). We're looking into it, so please don't pay again. Contact support if you need help.",
  'pay.notVerified.not_found': "We couldn't find that payment. Check the reference and try again.",
  'pay.notVerified.provider_mismatch': "That doesn't look like a payment to our account with this method. Check the method and the reference.",
  'pay.notVerified.pending': "Your payment isn't confirmed yet. Wait a minute and try again.",
  'pay.notVerified.invalid_request': "That reference doesn't look right. Check it and try again.",
  'pay.notVerified.unknown': "We couldn't confirm that payment. Check the reference and try again.",
  'pay.referenceUsed': 'That reference was already used for another order. Enter the reference of the payment you made for THIS order.',
  'pay.tryLater': "We couldn't check right now. Your order is safe. Try again in a moment.",
  'pay.closed': 'This order is no longer waiting for payment.',
  'pay.cancel': 'Cancel this order',
  'pay.cancelTitle': 'Cancel this order?',
  'pay.cancelBody': 'Your items go back to your cart. Only cancel if you have not sent any money.',
  'pay.cancelled': 'Order cancelled. Your items are back in your cart.',
  'pay.cancelFailed': "Couldn't cancel the order. It may already be paid or being checked.",
  'pay.items': 'In this order',
  'pay.viewOrders': 'View my orders',
  'pay.loadError': "Couldn't load this order. Check your connection and try again.",
  'status.pending_payment': 'Awaiting payment',
  'status.paid': 'Paid',
  'status.payment_mismatch': 'Under review',
  'status.cancelled': 'Cancelled',
  'order.note.pending_payment': 'Waiting for your payment. Open it to finish paying.',
  'order.note.paid': 'Payment confirmed.',
  'order.note.payment_mismatch': "Your transfer doesn't match the order total. We're reviewing it, so please don't pay again.",
  'order.note.cancelled': 'This order was cancelled.',
  'order.items': 'Items',
} as const;

/** Welcome, sign-in, sign-up and splash text (English). */
const AUTH_STRINGS_EN = {
  'auth.welcome': 'Welcome!',
  'auth.welcomeSub': 'Top up games and gift cards in seconds, paid in birr.',
  'auth.signUp': 'Sign up',
  'auth.login': 'Login',
  'auth.welcomeBack': 'Welcome Back!',
  'auth.loginSub': 'Log in to top up in seconds',
  'auth.email': 'Email address',
  'auth.emailPlaceholder': 'example@gmail.com',
  'auth.password': 'Password',
  'auth.passwordPlaceholder': 'Your password',
  'auth.passwordNew': 'At least 8 characters',
  'auth.wrongCreds': 'Wrong email or password.',
  'auth.signInFailed': 'Sign in failed.',
  'auth.confirmFirst': 'Please confirm your email first, then log in.',
  'auth.noAccount': 'Don\'t have an account?',
  'auth.haveAccount': 'Already have an account?',
  'auth.orLogin': 'or log in with',
  'auth.orSignUp': 'or sign up with',
  'auth.createAccount': 'Create Account',
  'auth.createSub': 'Enter your personal data',
  'auth.name': 'Your name',
  'auth.namePlaceholder': 'e.g. Abebe',
  'auth.nameShort': 'Display name must be at least 2 characters.',
  'auth.badEmail': 'Enter a valid email address.',
  'auth.passwordShort': 'Password must be at least 8 characters.',
  'auth.signUpFailed': 'Sign up failed.',
  'auth.alreadyRegistered': 'That email already has an account. Try signing in.',
  'auth.checkEmail': 'Check your email',
  'auth.sentLink': 'We sent a confirmation link to {email}',
  'auth.openLink': 'Open the link to activate your account, then log in.',
  'auth.goLogin': 'Go to login',
  'auth.google': 'Continue with Google',
  'auth.apple': 'Continue with Apple',
  'auth.notReady': 'Google and Apple sign-in need a development build. Coming next.',
  'auth.hidePassword': 'Hide password',
  'auth.showPassword': 'Show password',
  'splash.tagline': 'Diamonds, UC, gift cards and more.\nDelivered in seconds.',
  'splash.continue': 'Continue',
} as const;

/** The same, in Amharic. The two error messages that carry a technical reason from the server stay English. */
const AUTH_STRINGS_AM = {
  'auth.welcome': 'እንኳን ደህና መጡ!',
  'auth.welcomeSub': 'ጨዋታዎችንና የስጦታ ካርዶችን በሰከንዶች ውስጥ ይሙሉ፣ በብር ይክፈሉ።',
  'auth.signUp': 'ተመዝገብ',
  'auth.login': 'ግባ',
  'auth.welcomeBack': 'እንኳን በደህና ተመለሱ!',
  'auth.loginSub': 'በሰከንዶች ውስጥ ለመሙላት ይግቡ',
  'auth.email': 'ኢሜይል አድራሻ',
  'auth.emailPlaceholder': 'example@gmail.com',
  'auth.password': 'የይለፍ ቃል',
  'auth.passwordPlaceholder': 'የይለፍ ቃልዎ',
  'auth.passwordNew': 'ቢያንስ 8 ቁምፊዎች',
  'auth.wrongCreds': 'ኢሜይሉ ወይም የይለፍ ቃሉ የተሳሳተ ነው።',
  'auth.signInFailed': 'መግባት አልተቻለም።',
  'auth.confirmFirst': 'እባክዎ መጀመሪያ ኢሜይልዎን ያረጋግጡ፣ ከዚያ ይግቡ።',
  'auth.noAccount': 'መለያ የለዎትም?',
  'auth.haveAccount': 'መለያ አለዎት?',
  'auth.orLogin': 'ወይም በዚህ ይግቡ',
  'auth.orSignUp': 'ወይም በዚህ ይመዝገቡ',
  'auth.createAccount': 'መለያ ፍጠር',
  'auth.createSub': 'መረጃዎን ያስገቡ',
  'auth.name': 'ስምዎ',
  'auth.namePlaceholder': 'ለምሳሌ አበበ',
  'auth.nameShort': 'ስም ቢያንስ 2 ፊደላት መሆን አለበት።',
  'auth.badEmail': 'ትክክለኛ ኢሜይል አድራሻ ያስገቡ።',
  'auth.passwordShort': 'የይለፍ ቃል ቢያንስ 8 ቁምፊዎች መሆን አለበት።',
  'auth.signUpFailed': 'መመዝገብ አልተቻለም።',
  'auth.alreadyRegistered': 'ይህ ኢሜይል አስቀድሞ መለያ አለው። ለመግባት ይሞክሩ።',
  'auth.checkEmail': 'ኢሜይልዎን ይመልከቱ',
  'auth.sentLink': 'የማረጋገጫ አገናኝ ወደ {email} ልከናል',
  'auth.openLink': 'መለያዎን ለማንቃት አገናኙን ይክፈቱ፣ ከዚያ ይግቡ።',
  'auth.goLogin': 'ወደ መግቢያ ሂድ',
  'auth.google': 'በGoogle ቀጥል',
  'auth.apple': 'በApple ቀጥል',
  'auth.notReady': 'የGoogle እና Apple መግቢያ የልማት ግንባታ (development build) ያስፈልጋቸዋል። በቅርቡ ይመጣል።',
  'auth.hidePassword': 'የይለፍ ቃል ደብቅ',
  'auth.showPassword': 'የይለፍ ቃል አሳይ',
  'splash.tagline': 'ዳይመንድ፣ UC፣ የስጦታ ካርዶች እና ሌሎችም።\nበሰከንዶች ውስጥ ይላካል።',
  'splash.continue': 'ቀጥል',
} as const;

/** Newer screens' text: payment tutorials, receipts, product page, admin payment settings. */
const UI_STRINGS_EN = {
  'receipt.title': 'Receipt',
  'receipt.paymentMethod': 'Paid with',
  'receipt.wallet': 'Wallet',
  'receipt.reference': 'Transaction number',
  'receipt.paidOn': 'Paid on',
  'receipt.download': 'Download receipt',
  'receipt.shareTitle': 'Share receipt',
  'receipt.failed': 'Couldn\'t make the receipt. Try again.',
  'receipt.unavailable': 'Sharing isn\'t available on this device.',
  'receipt.thanks': 'Thank you for your order.',
  'receipt.notYet': 'A receipt appears here once your payment is confirmed.',
  'pay.tutorial': 'How to pay',
  'pay.tutorialImage': 'Picture {n} of {total}',
  'product.idFirst': 'Check your ID above first, then choose an amount.',
} as const;

/** The same, in Amharic (money-critical or unsure sentences stay English and are listed in AM_NEEDS_REVIEW). */
const UI_STRINGS_AM = {
  'receipt.title': 'ደረሰኝ',
  'receipt.paymentMethod': 'የተከፈለበት መንገድ',
  'receipt.wallet': 'ቦርሳ',
  'receipt.reference': 'የግብይት ቁጥር',
  'receipt.paidOn': 'የተከፈለበት ቀን',
  'receipt.download': 'ደረሰኝ አውርድ',
  'receipt.shareTitle': 'ደረሰኝ አጋራ',
  'receipt.failed': 'ደረሰኙን ማዘጋጀት አልተቻለም። እንደገና ይሞክሩ።',
  'receipt.unavailable': 'በዚህ መሳሪያ ማጋራት አይቻልም።',
  'receipt.thanks': 'ትዕዛዝዎን ስለሰጡን እናመሰግናለን።',
  'receipt.notYet': 'ክፍያዎ ሲረጋገጥ ደረሰኝ እዚህ ይታያል።',
  'pay.tutorial': 'እንዴት እንደሚከፍሉ',
  'pay.tutorialImage': 'ስዕል {n} ከ{total}',
  'product.idFirst': 'መጀመሪያ ከላይ መለያዎን ያረጋግጡ፣ ከዚያ መጠን ይምረጡ።',
} as const;

/**
 * Wallet text (balance pill, wallet, deposit, withdraw, buy now, paying from the wallet). English only for now, like CART_STRINGS:
 * money words must be written by a native speaker, so `am` reuses the English until then.
 */
const WALLET_STRINGS = {
  'tx.withdrawal': 'Withdrawal',

  'product.buyNow': 'Buy now',

  'wallet.title': 'Wallet',
  'wallet.balance': 'Balance',
  'wallet.open': 'Wallet, balance {amount}',
  'wallet.unavailable': 'Wallet, balance unavailable',
  'wallet.add': 'Add money',
  'wallet.deposit': 'Deposit',
  'wallet.withdraw': 'Withdraw',
  'wallet.history': 'History',
  'wallet.noHistory': 'No transactions yet.',
  'wallet.after': 'Balance {balance}',
  'wallet.openDeposit': 'Deposit of {amount} is waiting for your payment',
  'wallet.openDepositBody': 'Send the money, then enter the reference to add it to your balance.',
  'wallet.continue': 'Continue',
  'wallet.withdrawals': 'Your withdrawals',
  'wallet.wd.pending': 'Pending',
  'wallet.wd.approved': 'Approved',
  'wallet.wd.paid': 'Paid',
  'wallet.wd.declined': 'Declined',
  'wallet.declinedNote': 'Returned to your balance. Reason: {note}',

  'wallet.err.invalid_amount': 'That amount is not allowed.',
  'wallet.err.invalid_provider': 'Choose Telebirr or CBE.',
  'wallet.err.invalid_account': "That account number doesn't look right. Check it and try again.",
  'wallet.err.insufficient_balance': "You don't have enough balance for that.",
  'wallet.err.deposit_open': 'You already have a deposit waiting for payment.',
  'wallet.err.too_many_pending': 'You have too many withdrawals waiting. Wait for some to be handled first.',
  'wallet.err.unauthorized': 'Please sign in again.',
  'wallet.err.unavailable': "Couldn't reach the server. Check your connection and try again.",

  'deposit.title': 'Deposit',
  'deposit.lead': 'Add money to your balance by Telebirr or CBE. We add it as soon as your payment is verified.',
  'deposit.amount': 'Amount (Br)',
  'deposit.quick': 'Quick amounts',
  'deposit.start': 'Continue',
  'deposit.problem.required': 'Enter an amount.',
  'deposit.problem.min': 'The smallest deposit is {min}.',
  'deposit.problem.max': 'The largest deposit is {max}.',
  'deposit.sendExactly': 'Send exactly',
  'deposit.exactNote': 'Send this exact amount. A different amount cannot be added automatically.',
  'deposit.cancel': 'Change the amount',
  'deposit.cancelTitle': 'Change the amount?',
  'deposit.cancelBody': "This deposit will be cancelled. If you've already sent money, don't cancel: enter the reference instead.",
  'deposit.cancelFailed': "Couldn't cancel it. Try again.",
  'deposit.paidTitle': 'Deposit received',
  'deposit.paidBody': '{amount} was added to your balance.',
  'deposit.mismatchTitle': "The amount doesn't match",
  'deposit.mismatchBody': "We found your transfer, but not for {amount}. Nothing was added to your balance. We'll review it.",
  'deposit.done': 'Done',

  'withdraw.title': 'Withdraw',
  'withdraw.amount': 'Amount (Br)',
  'withdraw.to': 'Send my money to',
  'withdraw.account.telebirr': 'Your Telebirr number',
  'withdraw.account.cbe': 'Your CBE account number',
  'withdraw.account.required': 'Enter the account to send it to.',
  'withdraw.account.invalid': "That number doesn't look right.",
  'withdraw.accountHint.telebirr': 'The phone number registered with Telebirr, like 0911 22 33 44.',
  'withdraw.accountHint.cbe': 'Your 13-digit CBE account number.',
  'withdraw.problem.required': 'Enter an amount.',
  'withdraw.problem.min': 'The smallest withdrawal is {min}.',
  'withdraw.problem.balance': 'That is more than your balance ({balance}).',
  'withdraw.note':
    "The amount leaves your balance right away. We send it to the account above after checking, usually within a day. If we can't, it goes back to your balance and we tell you why.",
  'withdraw.submit': 'Request withdrawal',
  'withdraw.confirmTitle': 'Send to this account?',
  'withdraw.confirmBody': 'Send {amount} to {provider} {account}? Check the number: money sent to a wrong number cannot be recovered.',
  'withdraw.confirm': 'Request it',
  'withdraw.doneTitle': 'Request sent',
  'withdraw.doneBody': '{amount} is on hold. We will send it to {provider} {account} soon.',

  'cart.payWallet': 'Paid instantly from your wallet ({balance} available).',
  'cart.payBank': "Your wallet ({balance}) doesn't cover this, so you'll pay by Telebirr or CBE next.",
  'cart.checkoutWallet': 'Pay {amount} from wallet',

  'pay.wallet': 'Pay {amount} from wallet',
  'pay.walletOr': 'Your wallet covers this order',
  'pay.walletFailed': "Couldn't pay from the wallet. Your balance may have changed. Nothing was taken.",
  'pay.paidWalletBody': 'Paid from your wallet: {amount}.',
} as const;

export const en = {
  // tabs
  'tab.shop': 'Shop',
  'tab.orders': 'Orders',
  'tab.vault': 'Vault',
  'tab.profile': 'Profile',

  // accessibility hints for the tab dots
  'a11y.openOrders': '{n} open orders',
  'a11y.newCodes': '{n} new codes',

  // common
  'common.balance': 'Balance',
  'common.retry': 'Try again',
  'common.cancel': 'Cancel',
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.loadError': "Couldn't load this. Check your connection, then try again.",
  'common.topUp': 'Top up',

  // time
  'time.now': 'just now',
  'time.min': '{n}m ago',
  'time.hour': '{n}h ago',
  'time.day': '{n}d ago',

  // shop
  'shop.search': 'Search games, gift cards, keys',
  'shop.buyAgain': 'Buy again',
  'shop.loading': 'Loading products',
  'shop.seeAll': 'See all',
  'shop.seeAllIn': 'See all {name}',
  'shop.results': 'Results',
  'shop.noResults': 'No results for “{q}”',
  'shop.noResultsBody': 'Check the spelling, or search for a different game or gift card.',
  'shop.clear': 'Clear search',
  'shop.emptyTitle': 'Nothing here yet',
  'shop.emptyBody': 'New products show up here as soon as they are available.',
  'shop.errorTitle': "Couldn't load products",
  'shop.addBalance': "Adding balance isn't available yet.",
  'cat.gift-cards': 'Gift cards',
  'cat.game-keys': 'Game keys',
  'cat.games': 'Games',
  'cat.subscriptions': 'Subscriptions',

  // product / checkout
  'product.choose': 'Choose an amount',
  'product.gameId': 'Game ID',
  'product.gameIdHint': 'Enter your player ID exactly as it shows in the game.',
  'product.paste': 'Paste',
  'product.pay': 'Pay {price}',
  'product.yourBalance': 'Your balance',
  'product.notEnough': 'Not enough balance',
  'product.placed': 'Order placed',
  'product.placedTopup': "We'll deliver it to your game ID shortly.",
  'product.placedCode': "Your code will appear in the Vault as soon as it's ready.",
  'product.viewOrder': 'View order',
  'product.backToShop': 'Back to shop',
  'product.notFound': 'This product is no longer available.',
  'product.codeNote': 'You get a code. It is delivered to your Vault.',
  'product.topupNote': 'Delivered straight to your game ID.',
  'product.region': 'Region',
  'product.idTitle': 'Your player ID',
  'product.checking': 'Checking…',
  'product.playerRegion': 'Account region: {region}',
  'product.playerLabel': 'Player: {name}',
  'product.retry': 'Retry',
  'product.checkAgain': 'Check again',
  'product.check.invalid': "We couldn't find that player ID. Check it and try again.",
  'product.check.failed': "Couldn't check the ID right now.",
  'product.check.timeout': 'Checking is taking too long.',
  'product.check.expired': 'This check has expired. Check the ID again.',
  'product.regionAuto': 'Selected {region} to match your account.',
  'product.regionWrong': "Your account is in region {account}. Packs in {region} won't work for it.",
  'product.regionSwitch': 'Switch to {region}',
  'product.regionNone': "We don't sell this for accounts in region {account}.",
  'product.regionUnknown': "We couldn't confirm your account's region, so we can't sell region-specific packs for it.",
  'product.packWrongRegion': "Not for your account's region",
  'product.packUnknownRegion': "Region couldn't be confirmed",
  'product.packUnavailable': 'Not available',
  'product.tick': "I've checked my ID is correct. Top-ups can't be reversed.",
  'product.total': 'Total',
  'product.continue': 'Continue',
  'product.was': 'was {price}',
  'product.off': '{pct}% off',
  'product.blocker.choose': 'Choose a pack',
  'product.blocker.fill': 'Enter your ID',
  'product.blocker.checking': 'Checking your ID…',
  'product.blocker.invalid': 'Fix your ID to continue',
  'product.blocker.failed': 'Retry the ID check to continue',
  'product.blocker.expired': 'Check your ID again to continue',
  'product.blocker.confirm': 'Tick the box to continue',
  'product.blocker.wrongRegion': "Pick a pack for your account's region",
  'product.blocker.regionUnknown': "This pack can't be sold for your account",
  'product.blocker.unavailable': 'This pack is not available',
  'product.confirmTitle': 'Confirm your order',
  'product.item': 'Pack',
  'product.player': 'Player',
  'product.price': 'Price',
  'product.balanceAfter': 'Balance after',
  'product.confirmPay': 'Confirm and pay {price}',
  'product.cancel': 'Cancel',
  'product.verifying': 'Checking the latest price…',

  // errors
  'err.insufficient': 'Not enough balance. Top up and try again.',
  'err.unavailable': 'This item is no longer available.',
  'err.accountId': 'Enter a valid game ID.',
  'err.generic': 'Something went wrong. Please try again.',
  'err.packageGone': 'That package is no longer available.',
  'err.priceChanged': 'The price changed from {old} to {now}. Review it and continue when ready.',
  'err.idNotValidated': 'We need to check your ID again.',
  'err.idExpired': 'Your ID check expired. Check it again.',
  'err.idCheckRequired': 'Tick the box to confirm your ID.',
  'err.regionMismatch': "This pack isn't available for your account's region ({region}).",
  'err.regionUnverified': "We couldn't confirm your account's region, so this pack can't be bought.",

  // orders
  'orders.title': 'Orders',
  'orders.emptyTitle': 'No orders yet',
  'orders.emptyBody': 'Your purchases show up here.',
  'orders.detail': 'Order details',
  'order.item': 'Item',
  'order.amount': 'Amount',
  'order.placed': 'Placed',
  'order.gameId': 'Game ID',
  'order.region': 'Region',
  'order.verified': 'ID checked with the game before ordering',
  'order.verifiedPlayer': 'Player: {name}',
  'order.verifiedRegion': 'Account region: {region}',
  'order.selfDeclared': 'You confirmed this ID yourself',
  'order.number': 'Order',
  'order.viewVault': 'View in Vault',
  'order.note.pending': "We've received your order and will start on it soon.",
  'order.note.processing': "We're working on your order right now.",
  'order.note.completedTopup': 'Delivered to your game ID.',
  'order.note.completedCode': 'Your code is ready in the Vault.',
  'order.note.failed': "We couldn't deliver this order. {amount} was returned to your balance.",
  'order.note.refunded': '{amount} was returned to your balance.',
  'status.pending': 'Pending',
  'status.processing': 'Processing',
  'status.completed': 'Completed',
  'status.failed': 'Failed',
  'status.refunded': 'Refunded',

  // vault
  'vault.title': 'Vault',
  'vault.subtitle': 'Codes for gift cards, game keys and subscriptions.',
  'vault.emptyTitle': 'No codes yet',
  'vault.emptyBody':
    'Gift card, game key and subscription codes you buy show up here. Diamonds and UC go straight to your game ID.',
  'vault.reveal': 'Reveal',
  'vault.hide': 'Hide',
  'vault.used': 'Used',
  'vault.markUsed': 'Mark as used',
  'vault.codeCopied': 'Code copied',
  'vault.unused': 'Ready to use',

  // profile
  'profile.title': 'Profile',
  'profile.history': 'Transactions',
  'profile.noHistory': 'No transactions yet.',
  'profile.language': 'Language',
  'profile.support': 'Support',
  'profile.supportBody': 'Need help with an order or a top-up?',
  'profile.signOut': 'Sign out',
  'profile.adminView': 'Switch to admin view',
  'tx.deposit': 'Deposit',
  'tx.purchase': 'Purchase',
  'tx.refund': 'Refund',
  'tx.adjustment': 'Adjustment',

  // top up
  'topup.title': 'Top up',
  'topup.body':
    'Send your payment, then message us. We add the money to your balance as soon as we confirm it.',
  'topup.noContact': 'Ask the shop to add balance to your account.',
  'topup.account': 'Your account',
  'topup.contact': 'Contact support',
  ...CART_STRINGS,
  ...WALLET_STRINGS,
  ...AUTH_STRINGS_EN,
  ...UI_STRINGS_EN,
} as const;

export type StringKey = keyof typeof en;

/**
 * Amharic for the cart, payment, wallet, deposit and withdraw screens: short labels, statuses, buttons and plain messages.
 * Money-critical instruction sentences are NOT here: they stay English (see AM_NEEDS_REVIEW) until a native speaker approves
 * them, because a wrong word in "how to pay" or "what a mismatch means" costs someone money. Drafts: AMHARIC_REVIEW.md.
 */
const AM_CART_WALLET = {
  'cart.title': 'ጋሪ',
  'cart.empty': 'ጋሪዎ ባዶ ነው',
  'cart.emptyBody': 'ከጨዋታ ገጽ ጥቅሎችን ወደ ጋሪ ያክሉ፣ ከዚያ እዚህ ክፍያ ይፈጽሙ።',
  'cart.browse': 'ጨዋታዎችን ይመልከቱ',
  'cart.add': 'ወደ ጋሪ ጨምር',
  'cart.added': 'ወደ ጋሪ ተጨምሯል',
  'cart.remove': 'አስወግድ',
  'cart.qty': 'ብዛት',
  'cart.total': 'ጠቅላላ',
  'cart.checkout': 'ክፍያ ፈጽም',
  'cart.unavailable': 'ከዚህ በኋላ አይገኝም',
  'cart.unavailableBody': 'ለመቀጠል ያስወግዱት።',
  'cart.fixFirst': 'መጀመሪያ እነዚህን ያስተካክሉ፦',
  'cart.problem.fill_fields': 'መለያውን ያስገቡ',
  'cart.problem.checking': 'መለያውን በመፈተሽ ላይ…',
  'cart.problem.invalid_id': 'መለያው ትክክል አይደለም',
  'cart.problem.check_failed': 'መለያውን መፈተሽ አልተቻለም፣ እንደገና ይሞክሩ',
  'cart.problem.check_expired': 'የፍተሻው ጊዜ አልፏል፣ እንደገና ይፈትሹ',
  'cart.problem.confirm_id': 'መለያዎን እንደፈተሹ ምልክት ያድርጉ',
  'cart.problem.wrong_region': 'ይህ ጥቅል ለዚያ መለያ ክልል አይደለም',
  'cart.problem.region_unknown': 'የመለያው ክልል ሊረጋገጥ አልቻለም',
  'cart.problem.unavailable': 'ከዚህ በኋላ አይገኝም',
  'cart.problem.package_unavailable': 'አይገኝም',
  'cart.problem.choose_package': 'አይገኝም',
  'cart.dropped': 'እነዚህ እቃዎች ከዚህ በኋላ አይሸጡም፤ ተወግደዋል፦ {items}',
  'cart.fixIds': 'የእነዚህ እቃዎች የተጫዋች መለያ እንደገና መፈተሽ አለበት፦ {items}',
  'cart.checkoutFailed': 'ክፍያውን መጀመር አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'cart.loadError': 'ጋሪዎን መጫን አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'cart.pending': 'ክፍያ የሚጠብቅ ትዕዛዝ አለዎት።',
  'cart.payWallet': 'ወዲያውኑ ከቦርሳዎ ይከፈላል (ቀሪ ሂሳብ {balance})።',
  'cart.payBank': 'ቦርሳዎ ({balance}) ይህን አይሸፍንም፤ ስለዚህ በቀጣይ በቴሌብር ወይም በCBE ይከፍላሉ።',
  'cart.checkoutWallet': 'ከቦርሳ {amount} ክፈል',
  'pay.title': 'ክፍያ',
  'pay.amount': 'በትክክል ይላኩ',
  'pay.method': 'የመክፈያ መንገድ',
  'pay.telebirr': 'ቴሌብር',
  'pay.cbe': 'CBE',
  'pay.sendTo': 'የሚላክበት',
  'pay.accountName': 'የመለያ ስም',
  'pay.accountNumber': 'የመለያ ቁጥር',
  'pay.ref.telebirr': 'የቴሌብር የግብይት ቁጥር',
  'pay.ref.cbe': 'የCBE የግብይት መለያ',
  'pay.refHint.telebirr': 'በቴሌብር ደረሰኝዎ ወይም በአጭር መልዕክትዎ (SMS) ውስጥ ያገኙታል።',
  'pay.refHint.cbe': 'በCBE ደረሰኝዎ ወይም በአጭር መልዕክትዎ ላይ ያገኙታል። በFT ይጀምራል።',
  'pay.refRequired': 'ከክፍያ ደረሰኝዎ የግብይት ቁጥሩን ያስገቡ።',
  'pay.submit': 'ክፍያውን አረጋግጥ',
  'pay.verifying': 'ክፍያዎን በማረጋገጥ ላይ…',
  'pay.wait': 'አሁንም በማረጋገጥ ላይ ነው። ትንሽ ሊወስድ ይችላል።',
  'pay.paidTitle': 'ክፍያ ተረጋግጧል',
  'pay.paidBody': '{amount} ተቀብለናል። አመሰግናለን።',
  'pay.mismatchTitle': 'ክፍያዎን እየገመገምን ነው',
  'pay.closed': 'ይህ ትዕዛዝ ከዚህ በኋላ ክፍያ አይጠብቅም።',
  'pay.cancel': 'ትዕዛዙን ሰርዝ',
  'pay.cancelTitle': 'ትዕዛዙ ይሰረዝ?',
  'pay.cancelled': 'ትዕዛዙ ተሰርዟል። እቃዎችዎ ወደ ጋሪዎ ተመልሰዋል።',
  'pay.items': 'በዚህ ትዕዛዝ ውስጥ',
  'pay.viewOrders': 'ትዕዛዞቼን ተመልከት',
  'pay.loadError': 'ይህን ትዕዛዝ መጫን አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'pay.wallet': 'ከቦርሳ {amount} ክፈል',
  'pay.walletOr': 'ቦርሳዎ ይህን ትዕዛዝ ይሸፍናል',
  'pay.walletFailed': 'ከቦርሳ መክፈል አልተቻለም። ቀሪ ሂሳብዎ ተቀይሮ ሊሆን ይችላል። ምንም አልተወሰደም።',
  'pay.paidWalletBody': 'ከቦርሳዎ ተከፍሏል፦ {amount}።',
  'status.pending_payment': 'ክፍያ በመጠበቅ ላይ',
  'status.paid': 'ተከፍሏል',
  'status.payment_mismatch': 'በመገምገም ላይ',
  'status.cancelled': 'ተሰርዟል',
  'order.note.pending_payment': 'ክፍያዎን እየጠበቅን ነው። ለመጨረስ ይክፈቱት።',
  'order.note.paid': 'ክፍያ ተረጋግጧል።',
  'order.note.cancelled': 'ይህ ትዕዛዝ ተሰርዟል።',
  'order.items': 'እቃዎች',
  'tx.withdrawal': 'ወጪ',
  'product.buyNow': 'አሁን ግዛ',
  'wallet.title': 'ቦርሳ',
  'wallet.balance': 'ቀሪ ሂሳብ',
  'wallet.open': 'ቦርሳ፣ ቀሪ ሂሳብ {amount}',
  'wallet.unavailable': 'ቦርሳ፣ ቀሪ ሂሳብ አይገኝም',
  'wallet.add': 'ገንዘብ ጨምር',
  'wallet.deposit': 'ገንዘብ አስገባ',
  'wallet.withdraw': 'ገንዘብ አውጣ',
  'wallet.history': 'ታሪክ',
  'wallet.noHistory': 'ገና ምንም ግብይት የለም።',
  'wallet.after': 'ቀሪ ሂሳብ {balance}',
  'wallet.openDeposit': 'የ{amount} ገቢ ክፍያዎን እየጠበቀ ነው',
  'wallet.openDepositBody': 'ገንዘቡን ይላኩ፣ ከዚያ ወደ ቀሪ ሂሳብዎ ለመጨመር የግብይት ቁጥሩን ያስገቡ።',
  'wallet.continue': 'ቀጥል',
  'wallet.withdrawals': 'የገንዘብ ማውጫ ጥያቄዎችዎ',
  'wallet.wd.pending': 'በመጠበቅ ላይ',
  'wallet.wd.approved': 'ጸድቋል',
  'wallet.wd.paid': 'ተከፍሏል',
  'wallet.wd.declined': 'ውድቅ ተደርጓል',
  'wallet.declinedNote': 'ወደ ቀሪ ሂሳብዎ ተመልሷል። ምክንያት፦ {note}',
  'wallet.err.invalid_amount': 'ይህ መጠን አይፈቀድም።',
  'wallet.err.invalid_provider': 'ቴሌብር ወይም CBE ይምረጡ።',
  'wallet.err.invalid_account': 'የመለያ ቁጥሩ ትክክል አይመስልም። ያረጋግጡና እንደገና ይሞክሩ።',
  'wallet.err.insufficient_balance': 'ለዚህ በቂ ቀሪ ሂሳብ የለዎትም።',
  'wallet.err.deposit_open': 'ክፍያ የሚጠብቅ ገቢ አስቀድሞ አለዎት።',
  'wallet.err.too_many_pending': 'ብዙ የገንዘብ ማውጫ ጥያቄዎች በመጠበቅ ላይ ናቸው። መጀመሪያ አንዳንዶቹ እስኪስተናገዱ ይጠብቁ።',
  'wallet.err.unauthorized': 'እባክዎ እንደገና ይግቡ።',
  'wallet.err.unavailable': 'አገልጋዩን ማግኘት አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'deposit.title': 'ገንዘብ አስገባ',
  'deposit.lead': 'ወደ ቀሪ ሂሳብዎ በቴሌብር ወይም በCBE ገንዘብ ይጨምሩ። ክፍያዎ እንደተረጋገጠ እንጨምራለን።',
  'deposit.amount': 'መጠን (ብር)',
  'deposit.quick': 'ፈጣን መጠኖች',
  'deposit.start': 'ቀጥል',
  'deposit.problem.required': 'መጠን ያስገቡ።',
  'deposit.problem.min': 'ትንሹ ገቢ {min} ነው።',
  'deposit.problem.max': 'ትልቁ ገቢ {max} ነው።',
  'deposit.sendExactly': 'በትክክል ይላኩ',
  'deposit.cancel': 'መጠኑን ቀይር',
  'deposit.cancelTitle': 'መጠኑ ይቀየር?',
  'deposit.cancelFailed': 'መሰረዝ አልተቻለም። እንደገና ይሞክሩ።',
  'deposit.paidTitle': 'ገቢ ተቀብለናል',
  'deposit.paidBody': '{amount} ወደ ቀሪ ሂሳብዎ ተጨምሯል።',
  'deposit.mismatchTitle': 'መጠኑ አይመሳሰልም',
  'deposit.done': 'ተጠናቋል',
  'withdraw.title': 'ገንዘብ አውጣ',
  'withdraw.amount': 'መጠን (ብር)',
  'withdraw.to': 'ገንዘቤ የሚላክበት',
  'withdraw.account.telebirr': 'የቴሌብር ቁጥርዎ',
  'withdraw.account.cbe': 'የCBE መለያ ቁጥርዎ',
  'withdraw.account.required': 'የሚላክበትን መለያ ያስገቡ።',
  'withdraw.account.invalid': 'ቁጥሩ ትክክል አይመስልም።',
  'withdraw.accountHint.telebirr': 'በቴሌብር የተመዘገበው ስልክ ቁጥር፣ ለምሳሌ 0911 22 33 44።',
  'withdraw.accountHint.cbe': 'የ13 አሃዝ የCBE መለያ ቁጥርዎ።',
  'withdraw.problem.required': 'መጠን ያስገቡ።',
  'withdraw.problem.min': 'ትንሹ የማውጫ መጠን {min} ነው።',
  'withdraw.problem.balance': 'ይህ ከቀሪ ሂሳብዎ ({balance}) ይበልጣል።',
  'withdraw.submit': 'ማውጫ ጠይቅ',
  'withdraw.confirmTitle': 'ወደዚህ መለያ ይላክ?',
  'withdraw.confirm': 'ጠይቅ',
  'withdraw.doneTitle': 'ጥያቄው ተልኳል',
} as const;

/** Amharic strings that are still ENGLISH on purpose, waiting for a native speaker. A test keeps this list honest. */
export const AM_NEEDS_REVIEW = [
  'pay.noAccount',
  'pay.steps.telebirr',
  'pay.steps.cbe',
  'pay.mismatchBody',
  'pay.notVerified.not_found',
  'pay.notVerified.provider_mismatch',
  'pay.notVerified.pending',
  'pay.notVerified.invalid_request',
  'pay.notVerified.unknown',
  'pay.referenceUsed',
  'pay.tryLater',
  'pay.cancelBody',
  'pay.cancelFailed',
  'order.note.payment_mismatch',
  'deposit.exactNote',
  'deposit.cancelBody',
  'deposit.mismatchBody',
  'withdraw.note',
  'withdraw.confirmBody',
  'withdraw.doneBody',
] as const satisfies readonly StringKey[];

export const am: Record<StringKey, string> = {
  'tab.shop': 'ሱቅ',
  'tab.orders': 'ትዕዛዞች',
  'tab.vault': 'ካዝና',
  'tab.profile': 'መገለጫ',

  'a11y.openOrders': '{n} ክፍት ትዕዛዞች',
  'a11y.newCodes': '{n} አዲስ ኮዶች',

  'common.balance': 'ቀሪ ሂሳብ',
  'common.retry': 'እንደገና ሞክር',
  'common.cancel': 'ሰርዝ',
  'common.copy': 'ቅዳ',
  'common.copied': 'ተቀድቷል',
  'common.loadError': 'መጫን አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'common.topUp': 'ሂሳብ ሙላ',

  'time.now': 'አሁን',
  'time.min': 'ከ{n} ደቂቃ በፊት',
  'time.hour': 'ከ{n} ሰዓት በፊት',
  'time.day': 'ከ{n} ቀን በፊት',

  'shop.search': 'ጨዋታ፣ የስጦታ ካርድ፣ ቁልፍ ፈልግ',
  'shop.buyAgain': 'እንደገና ግዛ',
  'shop.loading': 'ምርቶች በመጫን ላይ',
  'shop.seeAll': 'ሁሉንም እይ',
  'shop.seeAllIn': 'ሁሉንም {name} እይ',
  'shop.results': 'ውጤቶች',
  'shop.noResults': 'ለ“{q}” ምንም ውጤት የለም',
  'shop.noResultsBody': 'ፊደሉን ያረጋግጡ ወይም ሌላ ጨዋታ ወይም የስጦታ ካርድ ይፈልጉ።',
  'shop.clear': 'ፍለጋውን አጽዳ',
  'shop.emptyTitle': 'እዚህ ገና ምንም የለም',
  'shop.emptyBody': 'አዳዲስ ምርቶች እንደተዘጋጁ እዚህ ይታያሉ።',
  'shop.errorTitle': 'ምርቶችን መጫን አልተቻለም',
  'shop.addBalance': 'ሂሳብ መሙላት ገና አይገኝም።',
  'cat.gift-cards': 'የስጦታ ካርዶች',
  'cat.game-keys': 'የጨዋታ ቁልፎች',
  'cat.games': 'ጨዋታዎች',
  'cat.subscriptions': 'ምዝገባዎች',

  'product.choose': 'መጠን ይምረጡ',
  'product.gameId': 'የጨዋታ መለያ (ID)',
  'product.gameIdHint': 'በጨዋታው ውስጥ እንደሚታየው የተጫዋች መለያዎን በትክክል ያስገቡ።',
  'product.paste': 'ለጥፍ',
  'product.pay': '{price} ክፈል',
  'product.yourBalance': 'ቀሪ ሂሳብዎ',
  'product.notEnough': 'በቂ ቀሪ ሂሳብ የለም',
  'product.placed': 'ትዕዛዝዎ ተልኳል',
  'product.placedTopup': 'በቅርቡ ወደ ጨዋታ መለያዎ እንልካለን።',
  'product.placedCode': 'ኮዱ እንደተዘጋጀ በካዝናዎ ውስጥ ይታያል።',
  'product.viewOrder': 'ትዕዛዙን እይ',
  'product.backToShop': 'ወደ ሱቅ ተመለስ',
  'product.notFound': 'ይህ ምርት ከእንግዲህ አይገኝም።',
  'product.codeNote': 'ኮድ ያገኛሉ። ወደ ካዝናዎ ይደርሳል።',
  'product.topupNote': 'በቀጥታ ወደ ጨዋታ መለያዎ ይላካል።',
  'product.region': 'ክልል',
  'product.idTitle': 'የተጫዋች መለያዎ',
  'product.checking': 'በመፈተሽ ላይ…',
  'product.playerRegion': 'የመለያ ክልል፦ {region}',
  'product.playerLabel': 'ተጫዋች፦ {name}',
  'product.retry': 'እንደገና ሞክር',
  'product.checkAgain': 'እንደገና ፈትሽ',
  'product.check.invalid': 'ያንን የተጫዋች መለያ ማግኘት አልተቻለም። ያረጋግጡና እንደገና ይሞክሩ።',
  'product.check.failed': 'መለያውን አሁን መፈተሽ አልተቻለም።',
  'product.check.timeout': 'ፍተሻው ከመጠን በላይ እየወሰደ ነው።',
  'product.check.expired': 'ይህ ፍተሻ ጊዜው አልፎበታል። መለያውን እንደገና ይፈትሹ።',
  'product.regionAuto': 'ከመለያዎ ጋር እንዲመሳሰል {region} ተመርጧል።',
  'product.regionWrong': 'መለያዎ በ{account} ክልል ውስጥ ነው። በ{region} ያሉ ጥቅሎች ለእሱ አይሰሩም።',
  'product.regionSwitch': 'ወደ {region} ቀይር',
  'product.regionNone': 'ይህንን በ{account} ክልል ላሉ መለያዎች አንሸጥም።',
  'product.regionUnknown': 'የመለያዎን ክልል ማረጋገጥ ስላልቻልን ለክልል የተወሰኑ ጥቅሎችን መሸጥ አንችልም።',
  'product.packWrongRegion': 'ለመለያዎ ክልል አይደለም',
  'product.packUnknownRegion': 'ክልሉ አልተረጋገጠም',
  'product.packUnavailable': 'አይገኝም',
  'product.tick': 'የመለያዬ ትክክለኛነት አረጋግጫለሁ። ግዢዎች መመለስ አይችሉም።',
  'product.total': 'ጠቅላላ',
  'product.continue': 'ቀጥል',
  'product.was': 'ቀድሞ {price}',
  'product.off': '{pct}% ቅናሽ',
  'product.blocker.choose': 'ጥቅል ይምረጡ',
  'product.blocker.fill': 'መለያዎን ያስገቡ',
  'product.blocker.checking': 'መለያዎ በመፈተሽ ላይ…',
  'product.blocker.invalid': 'ለመቀጠል መለያዎን ያስተካክሉ',
  'product.blocker.failed': 'ለመቀጠል ፍተሻውን እንደገና ይሞክሩ',
  'product.blocker.expired': 'ለመቀጠል መለያዎን እንደገና ይፈትሹ',
  'product.blocker.confirm': 'ለመቀጠል ሳጥኑን ምልክት ያድርጉ',
  'product.blocker.wrongRegion': 'ለመለያዎ ክልል የሚሆን ጥቅል ይምረጡ',
  'product.blocker.regionUnknown': 'ይህ ጥቅል ለመለያዎ ሊሸጥ አይችልም',
  'product.blocker.unavailable': 'ይህ ጥቅል አይገኝም',
  'product.confirmTitle': 'ትዕዛዝዎን ያረጋግጡ',
  'product.item': 'ጥቅል',
  'product.player': 'ተጫዋች',
  'product.price': 'ዋጋ',
  'product.balanceAfter': 'ከክፍያ በኋላ ቀሪ ሂሳብ',
  'product.confirmPay': 'አረጋግጥና {price} ክፈል',
  'product.cancel': 'ተው',
  'product.verifying': 'የቅርብ ጊዜውን ዋጋ በመፈተሽ ላይ…',

  'err.insufficient': 'በቂ ቀሪ ሂሳብ የለም። ሂሳብ ሞልተው እንደገና ይሞክሩ።',
  'err.unavailable': 'ይህ ምርት ከእንግዲህ አይገኝም።',
  'err.accountId': 'ትክክለኛ የጨዋታ መለያ ያስገቡ።',
  'err.generic': 'የሆነ ችግር ተፈጥሯል። እባክዎ እንደገና ይሞክሩ።',
  'err.packageGone': 'ያ ጥቅል ከእንግዲህ አይገኝም።',
  'err.priceChanged': 'ዋጋው ከ{old} ወደ {now} ተቀይሯል። ይመልከቱና ዝግጁ ሲሆኑ ይቀጥሉ።',
  'err.idNotValidated': 'መለያዎን እንደገና መፈተሽ አለብን።',
  'err.idExpired': 'የመለያ ፍተሻዎ ጊዜው አልፏል። እንደገና ይፈትሹ።',
  'err.idCheckRequired': 'መለያዎን ለማረጋገጥ ሳጥኑን ምልክት ያድርጉ።',
  'err.regionMismatch': 'ይህ ጥቅል ለመለያዎ ክልል ({region}) አይገኝም።',
  'err.regionUnverified': 'የመለያዎን ክልል ማረጋገጥ ስላልቻልን ይህ ጥቅል መገዛት አይችልም።',

  'orders.title': 'ትዕዛዞች',
  'orders.emptyTitle': 'ገና ምንም ትዕዛዝ የለም',
  'orders.emptyBody': 'ግዢዎችዎ እዚህ ይታያሉ።',
  'orders.detail': 'የትዕዛዝ ዝርዝር',
  'order.item': 'ምርት',
  'order.amount': 'መጠን',
  'order.placed': 'የታዘዘበት ጊዜ',
  'order.gameId': 'የጨዋታ መለያ',
  'order.region': 'ክልል',
  'order.verified': 'መለያው ከማዘዙ በፊት ከጨዋታው ጋር ተፈትሿል',
  'order.verifiedPlayer': 'ተጫዋች፦ {name}',
  'order.verifiedRegion': 'የመለያ ክልል፦ {region}',
  'order.selfDeclared': 'ይህንን መለያ እርስዎ ራስዎ አረጋግጠዋል',
  'order.number': 'ትዕዛዝ',
  'order.viewVault': 'በካዝና ውስጥ እይ',
  'order.note.pending': 'ትዕዛዝዎን ተቀብለናል፤ በቅርቡ እንጀምራለን።',
  'order.note.processing': 'ትዕዛዝዎን አሁን እየሠራንበት ነው።',
  'order.note.completedTopup': 'ወደ ጨዋታ መለያዎ ተልኳል።',
  'order.note.completedCode': 'ኮዱ በካዝናዎ ውስጥ ተዘጋጅቷል።',
  'order.note.failed': 'ይህን ትዕዛዝ ማድረስ አልቻልንም። {amount} ወደ ቀሪ ሂሳብዎ ተመልሷል።',
  'order.note.refunded': '{amount} ወደ ቀሪ ሂሳብዎ ተመልሷል።',
  'status.pending': 'በመጠባበቅ ላይ',
  'status.processing': 'በሂደት ላይ',
  'status.completed': 'ተጠናቋል',
  'status.failed': 'አልተሳካም',
  'status.refunded': 'ተመላሽ ተደርጓል',

  'vault.title': 'ካዝና',
  'vault.subtitle': 'የስጦታ ካርድ፣ የጨዋታ ቁልፍ እና የምዝገባ ኮዶች።',
  'vault.emptyTitle': 'ገና ምንም ኮድ የለም',
  'vault.emptyBody':
    'የገዙት የስጦታ ካርድ፣ የጨዋታ ቁልፍ እና የምዝገባ ኮዶች እዚህ ይታያሉ። ዳይመንድና UC በቀጥታ ወደ ጨዋታ መለያዎ ይላካሉ።',
  'vault.reveal': 'አሳይ',
  'vault.hide': 'ደብቅ',
  'vault.used': 'ጥቅም ላይ ውሏል',
  'vault.markUsed': 'እንደዋለ ምልክት አድርግ',
  'vault.codeCopied': 'ኮዱ ተቀድቷል',
  'vault.unused': 'ለመጠቀም ዝግጁ',

  'profile.title': 'መገለጫ',
  'profile.history': 'ግብይቶች',
  'profile.noHistory': 'ገና ምንም ግብይት የለም።',
  'profile.language': 'ቋንቋ',
  'profile.support': 'ድጋፍ',
  'profile.supportBody': 'ስለ ትዕዛዝ ወይም ሂሳብ መሙላት እርዳታ ይፈልጋሉ?',
  'profile.signOut': 'ውጣ',
  'profile.adminView': 'ወደ አስተዳዳሪ እይታ ቀይር',
  'tx.deposit': 'ገቢ',
  'tx.purchase': 'ግዢ',
  'tx.refund': 'ተመላሽ',
  'tx.adjustment': 'ማስተካከያ',

  'topup.title': 'ሂሳብ ሙላ',
  'topup.body': 'ክፍያዎን ይላኩና ይጻፉልን። ክፍያውን እንዳረጋገጥን ገንዘቡን ወደ ቀሪ ሂሳብዎ እንጨምራለን።',
  'topup.noContact': 'ወደ ሂሳብዎ ገንዘብ እንዲጨመርልዎ ሱቁን ይጠይቁ።',
  'topup.account': 'የእርስዎ መለያ',
  'topup.contact': 'ድጋፍን አግኙ',
  // English placeholders first, then the Amharic that exists (AM_CART_WALLET) overrides them. See AM_NEEDS_REVIEW.
  ...CART_STRINGS,
  ...WALLET_STRINGS,
  ...AUTH_STRINGS_AM,
  ...UI_STRINGS_AM,
  ...AM_CART_WALLET,
};
