/**
 * Customer-facing text. English is the source of truth: TypeScript fails the
 * build if an Amharic string is missing. Have a native speaker review the
 * Amharic before launch. Admin screens are English only.
 */
/**
 * Cart, checkout and payment text. English only for now: the Amharic copy of these screens must be written by a
 * native speaker (a wrong word in a payment instruction costs money), so `am` reuses the English until then.
 */
const CART_STRINGS = {
  'cart.title': 'Cart',
  'cart.empty': 'Your cart is empty',
  'cart.emptyBody': 'Add packs from a game page, then check out here.',
  'cart.browse': 'Browse games',
  'cart.add': 'Add to cart',
  'cart.added': 'Added to cart',
  'cart.remove': 'Remove',
  'cart.qty': 'Quantity',
  'cart.total': 'Total',
  'cart.checkout': 'Check out',
  'cart.unavailable': 'No longer available',
  'cart.unavailableBody': 'Remove it to continue.',
  'cart.fixFirst': 'Fix these first:',
  'cart.problem.fill_fields': 'enter the ID',
  'cart.problem.checking': 'checking the ID…',
  'cart.problem.invalid_id': "the ID isn't valid",
  'cart.problem.check_failed': "couldn't check the ID, tap Retry",
  'cart.problem.check_expired': 'the ID check ran out, check it again',
  'cart.problem.confirm_id': 'tick that you checked the ID',
  'cart.problem.wrong_region': "this pack isn't for that account's region",
  'cart.problem.region_unknown': "the account's region couldn't be confirmed",
  'cart.problem.unavailable': 'no longer available',
  'cart.problem.package_unavailable': 'not available',
  'cart.problem.choose_package': 'not available',
  'cart.dropped': 'These items are no longer for sale and were removed: {items}',
  'cart.fixIds': 'These items need their player ID checked again: {items}',
  'cart.checkoutFailed': "Couldn't start checkout. Check your connection and try again.",
  'cart.loadError': "Couldn't load your cart. Check your connection and try again.",
  'cart.pending': 'You have an order waiting for payment.',
  'cart.codeLabel': 'Discount code (optional)',
  'cart.codePlaceholder': 'Enter code',
  'cart.codeApply': 'Apply',
  'cart.codeApplyPercent': 'Apply -{percent}%',
  'cart.codeApplied': 'Code applied: -{amount}',
  'cart.codeChecking': 'Checking code…',
  'cart.code.notFound': "That code doesn't exist. Check it and try again.",
  'cart.code.inactive': "That code isn't active any more.",
  'cart.code.expired': 'That code has expired.',
  'cart.code.notApplicable': "That code doesn't apply to anything in your cart.",
  'cart.code.alreadyUsed': "You've already used this code.",
  'cart.code.alreadyUsedBonus': "Already used — you'll get +{n} Portal Coins instead of a discount.",
  'cart.wheelUnavailable': 'That prize is no longer available.',
  'pay.title': 'Pay',
  'pay.amount': 'Send exactly',
  'pay.method': 'Pay with',
  'pay.telebirr': 'Telebirr',
  'pay.cbe': 'CBE',
  'pay.sendTo': 'Send to',
  'pay.accountName': 'Account name',
  'pay.accountNumber': 'Account number',
  'pay.noAccount': 'This payment method is not available yet. Try the other one, or contact support.',
  'pay.steps.telebirr': 'Send the amount above by Telebirr to this number, then enter the transaction number from your receipt below.',
  'pay.steps.cbe': 'Send the amount above to this CBE account, then enter the transaction ID from your receipt below (it starts with FT).',
  'pay.ref.telebirr': 'Telebirr transaction number',
  'pay.ref.cbe': 'CBE transaction ID',
  'pay.refHint.telebirr': 'Find it in your Telebirr receipt or SMS.',
  'pay.refHint.cbe': 'Find it on your CBE receipt or SMS. It starts with FT.',
  'pay.refRequired': 'Enter the reference from your payment receipt.',
  'pay.submit': 'Verify payment',
  'pay.verifying': 'Checking your payment…',
  'pay.wait': 'Still checking. This can take a moment.',
  'pay.paidTitle': 'Payment successful!',
  'pay.paidBody': "You'll receive your product shortly.",
  'pay.viewReceipt': 'View receipt',
  'pay.moreItems': '+{n} more',
  'pay.mismatchTitle': "We're reviewing your payment",
  'pay.mismatchBody': "We found your transfer, but its amount doesn't match this order ({amount}). We're looking into it, so please don't pay again. Contact support if you need help.",
  'pay.notVerified.not_found': "We couldn't find that payment. Check the reference and try again.",
  'pay.notVerified.provider_mismatch': "That doesn't look like a payment to our account with this method. Check the method and the reference.",
  'pay.notVerified.pending': "Your payment isn't confirmed yet. Wait a minute and try again.",
  'pay.notVerified.invalid_request': "That reference doesn't look right. Check it and try again.",
  'pay.notVerified.unknown': "We couldn't confirm that payment. Check the reference and try again.",
  'pay.referenceUsed': 'That reference was already used for another order. Enter the reference of the payment you made for THIS order.',
  'pay.tryLater': "We couldn't check right now. Your order is safe. Try again in a moment.",
  'pay.closed': 'This order is no longer waiting for payment.',
  'pay.cancel': 'Cancel this order',
  'pay.cancelTitle': 'Cancel this order?',
  'pay.cancelBody': 'Your items go back to your cart. Only cancel if you have not sent any money.',
  'pay.cancelled': 'Order cancelled. Your items are back in your cart.',
  'pay.cancelFailed': "Couldn't cancel the order. It may already be paid or being checked.",
  'pay.items': 'In this order',
  'pay.viewOrders': 'View my orders',
  'pay.viewVault': 'Go to my Vault',
  'pay.loadError': "Couldn't load this order. Check your connection and try again.",
  'status.pending_payment': 'Awaiting payment',
  'status.paid': 'Paid',
  'status.payment_mismatch': 'Under review',
  'status.cancelled': 'Cancelled',
  'order.note.pending_payment': 'Waiting for your payment. Open it to finish paying.',
  'order.note.paid': 'Payment confirmed.',
  'order.note.payment_mismatch': "Your transfer doesn't match the order total. We're reviewing it, so please don't pay again.",
  'order.note.cancelled': 'This order was cancelled.',
  'order.items': 'Items',
} as const;

/** Welcome, sign-in, sign-up and splash text (English). */
const AUTH_STRINGS_EN = {
  'auth.signUp': 'Sign up',
  'auth.login': 'Login',
  'auth.welcomeBack': 'Welcome Back!',
  'auth.loginSub': 'Log in to top up in seconds',
  'auth.email': 'Email address',
  'auth.emailPlaceholder': 'example@gmail.com',
  'auth.password': 'Password',
  'auth.passwordPlaceholder': 'Your password',
  'auth.passwordNew': 'At least 8 characters',
  'auth.wrongCreds': 'Wrong email or password.',
  'auth.signInFailed': 'Sign in failed.',
  'auth.confirmFirst': 'Please confirm your email first, then log in.',
  'auth.noAccount': 'Don\'t have an account?',
  'auth.haveAccount': 'Already have an account?',
  'auth.orLogin': 'or log in with',
  'auth.orSignUp': 'or sign up with',
  'auth.createAccount': 'Create Account',
  'auth.createSub': 'Enter your personal data',
  'auth.name': 'Your name',
  'auth.namePlaceholder': 'e.g. Abebe',
  'auth.nameShort': 'Display name must be at least 2 characters.',
  'auth.badEmail': 'Enter a valid email address.',
  'auth.passwordShort': 'Password must be at least 8 characters.',
  'auth.signUpFailed': 'Sign up failed.',
  'auth.alreadyRegistered': 'That email already has an account. Try signing in.',
  'auth.checkEmail': 'Check your email',
  'auth.sentLink': 'We sent a confirmation link to {email}',
  'auth.openLink': 'Open the link to activate your account, then log in.',
  'auth.goLogin': 'Go to login',
  'auth.google': 'Continue with Google',
  'auth.googleFailed': "Couldn't continue with Google. Check your connection and try again.",
  'auth.hidePassword': 'Hide password',
  'auth.showPassword': 'Show password',
  'splash.orContinue': 'or continue with',
  'splash.s1.title': 'Your favorite games,\nall in one app',
  'splash.s1.sub': 'Steam, Free Fire, PUBG, Telegram and more, paid in birr.',
  'splash.s2.title': 'Delivered\nin seconds',
  'splash.s2.sub': 'Pay with Telebirr, CBE or your wallet, and we get it to you fast.',
  'splash.s3.title': 'Best prices,\nreal savings',
  'splash.s3.sub': 'Fair birr prices, discount codes and rewards on every order.',
  'username.title': 'Choose a username',
  'username.subtitle': "One more thing before you're in.",
  'username.placeholder': 'e.g. Abebe',
  'username.continue': 'Continue',
  'username.failed': "Couldn't save that. Try again.",
} as const;

/** The same, in Amharic. The two error messages that carry a technical reason from the server stay English. */
const AUTH_STRINGS_AM = {
  'auth.signUp': 'ተመዝገብ',
  'auth.login': 'ግባ',
  'auth.welcomeBack': 'እንኳን በደህና ተመለሱ!',
  'auth.loginSub': 'በሰከንዶች ውስጥ ለመሙላት ይግቡ',
  'auth.email': 'ኢሜይል አድራሻ',
  'auth.emailPlaceholder': 'example@gmail.com',
  'auth.password': 'የይለፍ ቃል',
  'auth.passwordPlaceholder': 'የይለፍ ቃልዎ',
  'auth.passwordNew': 'ቢያንስ 8 ቁምፊዎች',
  'auth.wrongCreds': 'ኢሜይሉ ወይም የይለፍ ቃሉ የተሳሳተ ነው።',
  'auth.signInFailed': 'መግባት አልተቻለም።',
  'auth.confirmFirst': 'እባክዎ መጀመሪያ ኢሜይልዎን ያረጋግጡ፣ ከዚያ ይግቡ።',
  'auth.noAccount': 'መለያ የለዎትም?',
  'auth.haveAccount': 'መለያ አለዎት?',
  'auth.orLogin': 'ወይም በዚህ ይግቡ',
  'auth.orSignUp': 'ወይም በዚህ ይመዝገቡ',
  'auth.createAccount': 'መለያ ፍጠር',
  'auth.createSub': 'መረጃዎን ያስገቡ',
  'auth.name': 'ስምዎ',
  'auth.namePlaceholder': 'ለምሳሌ አበበ',
  'auth.nameShort': 'ስም ቢያንስ 2 ፊደላት መሆን አለበት።',
  'auth.badEmail': 'ትክክለኛ ኢሜይል አድራሻ ያስገቡ።',
  'auth.passwordShort': 'የይለፍ ቃል ቢያንስ 8 ቁምፊዎች መሆን አለበት።',
  'auth.signUpFailed': 'መመዝገብ አልተቻለም።',
  'auth.alreadyRegistered': 'ይህ ኢሜይል አስቀድሞ መለያ አለው። ለመግባት ይሞክሩ።',
  'auth.checkEmail': 'ኢሜይልዎን ይመልከቱ',
  'auth.sentLink': 'የማረጋገጫ አገናኝ ወደ {email} ልከናል',
  'auth.openLink': 'መለያዎን ለማንቃት አገናኙን ይክፈቱ፣ ከዚያ ይግቡ።',
  'auth.goLogin': 'ወደ መግቢያ ሂድ',
  'auth.google': 'በGoogle ቀጥል',
  'auth.googleFailed': 'በGoogle መቀጠል አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'auth.hidePassword': 'የይለፍ ቃል ደብቅ',
  'auth.showPassword': 'የይለፍ ቃል አሳይ',
  'splash.orContinue': 'ወይም በዚህ ይቀጥሉ',
  'splash.s1.title': 'የሚወዷቸው ጨዋታዎች\nበሙሉ በአንድ ቦታ',
  'splash.s1.sub': 'Steam፣ Free Fire፣ PUBG፣ Telegram እና ሌሎችም፣ በብር ይክፈሉ።',
  'splash.s2.title': 'በሰከንዶች\nውስጥ ይደርሳል',
  'splash.s2.sub': 'በቴሌብር፣ በCBE ወይም በዋሌትዎ ይክፈሉ፤ በፍጥነት እናደርስልዎታለን።',
  'splash.s3.title': 'ምርጥ ዋጋ፣\nእውነተኛ ቁጠባ',
  'splash.s3.sub': 'ፍትሃዊ የብር ዋጋ፣ የቅናሽ ኮዶች እና በእያንዳንዱ ትዕዛዝ ሽልማቶች።',
  'username.title': 'የተጠቃሚ ስም ይምረጡ',
  'username.subtitle': 'ከመግባትዎ በፊት አንድ ተጨማሪ ነገር።',
  'username.placeholder': 'ለምሳሌ አበበ',
  'username.continue': 'ቀጥል',
  'username.failed': 'ማስቀመጥ አልተቻለም። እንደገና ይሞክሩ።',
} as const;

/** Newer screens' text: payment tutorials, receipts, product page, admin payment settings. */
const UI_STRINGS_EN = {
  'receipt.title': 'Receipt',
  'receipt.paymentMethod': 'Paid with',
  'receipt.wallet': 'Wallet',
  'receipt.reference': 'Transaction number',
  'receipt.paidOn': 'Paid on',
  'receipt.download': 'Download receipt',
  'receipt.shareTitle': 'Share receipt',
  'receipt.failed': 'Couldn\'t make the receipt. Try again.',
  'receipt.unavailable': 'Sharing isn\'t available on this device.',
  'receipt.thanks': 'Thank you for your order.',
  'receipt.notYet': 'A receipt appears here once your payment is confirmed.',
  'pay.tutorial': 'How to pay',
  'pay.tutorialImage': 'Picture {n} of {total}',
  'product.idFirst': 'Check your ID above first, then choose an amount.',
} as const;

/** The same, in Amharic (money-critical or unsure sentences stay English and are listed in AM_NEEDS_REVIEW). */
const UI_STRINGS_AM = {
  'receipt.title': 'ደረሰኝ',
  'receipt.paymentMethod': 'የተከፈለበት መንገድ',
  'receipt.wallet': 'ቦርሳ',
  'receipt.reference': 'የግብይት ቁጥር',
  'receipt.paidOn': 'የተከፈለበት ቀን',
  'receipt.download': 'ደረሰኝ አውርድ',
  'receipt.shareTitle': 'ደረሰኝ አጋራ',
  'receipt.failed': 'ደረሰኙን ማዘጋጀት አልተቻለም። እንደገና ይሞክሩ።',
  'receipt.unavailable': 'በዚህ መሳሪያ ማጋራት አይቻልም።',
  'receipt.thanks': 'ትዕዛዝዎን ስለሰጡን እናመሰግናለን።',
  'receipt.notYet': 'ክፍያዎ ሲረጋገጥ ደረሰኝ እዚህ ይታያል።',
  'pay.tutorial': 'እንዴት እንደሚከፍሉ',
  'pay.tutorialImage': 'ስዕል {n} ከ{total}',
  'product.idFirst': 'መጀመሪያ ከላይ መለያዎን ያረጋግጡ፣ ከዚያ መጠን ይምረጡ።',
} as const;

/** The prize wheel: the customer's own screen, and the cart's "you have a discount" pill. */
const WHEEL_STRINGS_EN = {
  'tab.wheel': 'Wheel',
  'wheel.title': 'Prize Wheel',
  'wheel.lead': 'Spin to win a birr-off discount. The prize is picked fairly before the wheel even starts moving.',
  'wheel.emptyTitle': 'No prizes right now',
  'wheel.emptyBody': 'Check back soon.',
  'wheel.creditsLeft': '{n} spins left',
  'wheel.spin': 'Spin',
  'wheel.spinning': 'Spinning…',
  'wheel.needCredits': 'Buy spins below to play.',
  'wheel.buySpins': 'Buy spins',
  'wheel.noPackages': 'No spin packages available right now.',
  'wheel.spinsCount': '{n} spin(s)',
  'wheel.buyFor': '{n} Portal Coins',
  'wheel.boughtSpins': '+{n} spins added',
  'wheel.wonTitle': 'You won!',
  'wheel.wonAmount': '{amount} off',
  'wheel.wonHint': 'Use it at checkout on your next order.',
  'wheel.wonButton': 'Nice!',
  'cart.wheelPillLabel': '{amount} available',
  'cart.wheelPillLabelMulti': '{n} prizes available',
  'cart.wheelUse': 'Use',
  'cart.wheelChoose': 'Choose',
  'cart.wheelPickerTitle': 'Choose a prize',
  'cart.wheelWonOn': 'Won {date}',
  'cart.wheelApplied': 'Prize applied: -{amount}',
} as const;

/** The same, in Amharic. */
const WHEEL_STRINGS_AM = {
  'tab.wheel': 'መንኮራኩር',
  'wheel.title': 'የሽልማት መንኮራኩር',
  'wheel.lead': 'ብር-ቅናሽ ለማሸነፍ ያሽከርክሩ። መንኮራኩሩ ከመንቀሳቀሱ በፊት ሽልማቱ በትክክል ተመርጧል።',
  'wheel.emptyTitle': 'አሁን ምንም ሽልማት የለም',
  'wheel.emptyBody': 'ቆይተው ይመልከቱ።',
  'wheel.creditsLeft': '{n} ዙሮች ቀርተዋል',
  'wheel.spin': 'አሽከርክር',
  'wheel.spinning': 'በማሽከርከር ላይ…',
  'wheel.needCredits': 'ለመጫወት ከታች ዙሮችን ይግዙ።',
  'wheel.buySpins': 'ዙሮችን ግዛ',
  'wheel.noPackages': 'አሁን የዙር ጥቅሎች የሉም።',
  'wheel.spinsCount': '{n} ዙር(ዎች)',
  'wheel.buyFor': '{n} ፖርታል ኮይኖች',
  'wheel.boughtSpins': '+{n} ዙሮች ታክለዋል',
  'wheel.wonTitle': 'አሸንፈዋል!',
  'wheel.wonAmount': '{amount} ቅናሽ',
  'wheel.wonHint': 'በሚቀጥለው ትዕዛዝዎ ክፍያ ጊዜ ይጠቀሙበት።',
  'wheel.wonButton': 'ጎሽ!',
  'cart.wheelPillLabel': '{amount} ይገኛል',
  'cart.wheelPillLabelMulti': '{n} ሽልማቶች ይገኛሉ',
  'cart.wheelUse': 'ተጠቀም',
  'cart.wheelChoose': 'ምረጥ',
  'cart.wheelPickerTitle': 'ሽልማት ይምረጡ',
  'cart.wheelWonOn': '{date} ላይ ተሸልመዋል',
  'cart.wheelApplied': 'ሽልማት ተተግብሯል፦ -{amount}',
} as const;

/** The shop header: language button, cart button, wallet pill and its dropdown menu. */
const HEADER_STRINGS_EN = {
  'header.changeLanguage': 'Change language',
  'header.cart': 'Cart',
  'header.cartItems': 'Cart, {n} items',
  'header.wallet': 'Wallet balance {amount}',
  'header.walletUnavailable': 'Wallet balance unavailable',
  'header.topUp': 'Top up',
  'header.walletBalanceLabel': 'Wallet balance',
  'header.rewardPoints': 'Reward points',
  'header.topUpWallet': '+ Top up wallet',
  'header.signIn': 'Sign in',
} as const;

/** The same, in Amharic. */
const HEADER_STRINGS_AM = {
  'header.changeLanguage': 'ቋንቋ ቀይር',
  'header.cart': 'ጋሪ',
  'header.cartItems': 'ጋሪ፣ {n} ዕቃዎች',
  'header.wallet': 'የቦርሳ ቀሪ ሂሳብ {amount}',
  'header.walletUnavailable': 'የቦርሳ ቀሪ ሂሳብ አይገኝም',
  'header.topUp': 'ሂሳብ ሙላ',
  'header.walletBalanceLabel': 'የቦርሳ ቀሪ ሂሳብ',
  'header.rewardPoints': 'የሽልማት ነጥቦች',
  'header.topUpWallet': '+ ቦርሳ ሙላ',
  'header.signIn': 'ግባ',
} as const;

/**
 * Wallet text (balance pill, wallet, deposit, withdraw, buy now, paying from the wallet). English only for now, like CART_STRINGS:
 * money words must be written by a native speaker, so `am` reuses the English until then.
 */
const WALLET_STRINGS = {
  'tx.withdrawal': 'Withdrawal',
  'tx.commission': 'Commission',
  'tx.portal_coin_redemption': 'Portal Coins redeemed',

  'product.buyNow': 'Buy now',

  'wallet.title': 'Wallet',
  'wallet.balance': 'Balance',
  'wallet.deposit': 'Deposit',
  'wallet.withdraw': 'Withdraw',
  'wallet.history': 'History',
  'wallet.noHistory': 'No transactions yet.',
  'wallet.after': 'Balance {balance}',
  'wallet.openDeposit': 'Deposit of {amount} is waiting for your payment',
  'wallet.openDepositBody': 'Send the money, then enter the reference to add it to your balance.',
  'wallet.continue': 'Continue',
  'wallet.withdrawals': 'Your withdrawals',
  'wallet.wd.pending': 'Pending',
  'wallet.wd.approved': 'Approved',
  'wallet.wd.paid': 'Paid',
  'wallet.wd.declined': 'Declined',
  'wallet.declinedNote': 'Returned to your balance. Reason: {note}',

  'portalCoin.balance': '{n} Portal Coins',
  'portalCoin.earned': '+{n} Portal Coins earned',

  'wallet.err.invalid_amount': 'That amount is not allowed.',
  'wallet.err.invalid_provider': 'Choose Telebirr or CBE.',
  'wallet.err.invalid_account': "That account number doesn't look right. Check it and try again.",
  'wallet.err.insufficient_balance': "You don't have enough balance for that.",
  'wallet.err.deposit_open': 'You already have a deposit waiting for payment.',
  'wallet.err.too_many_pending': 'You have too many withdrawals waiting. Wait for some to be handled first.',
  'wallet.err.unauthorized': 'Please sign in again.',
  'wallet.err.unavailable': "Couldn't reach the server. Check your connection and try again.",

  'deposit.title': 'Deposit',
  'deposit.lead': 'Add money to your balance by Telebirr or CBE. We add it as soon as your payment is verified.',
  'deposit.amount': 'Amount (Br)',
  'deposit.quick': 'Quick amounts',
  'deposit.start': 'Continue',
  'deposit.problem.required': 'Enter an amount.',
  'deposit.problem.min': 'The smallest deposit is {min}.',
  'deposit.problem.max': 'The largest deposit is {max}.',
  'deposit.sendExactly': 'Send exactly',
  'deposit.exactNote': 'Send this exact amount. A different amount cannot be added automatically.',
  'deposit.cancel': 'Change the amount',
  'deposit.cancelTitle': 'Change the amount?',
  'deposit.cancelBody': "This deposit will be cancelled. If you've already sent money, don't cancel: enter the reference instead.",
  'deposit.cancelFailed': "Couldn't cancel it. Try again.",
  'deposit.paidTitle': 'Deposit received',
  'deposit.paidBody': '{amount} was added to your balance.',
  'deposit.mismatchTitle': "The amount doesn't match",
  'deposit.mismatchBody': "We found your transfer, but not for {amount}. Nothing was added to your balance. We'll review it.",
  'deposit.done': 'Done',

  'withdraw.title': 'Withdraw',
  'withdraw.amount': 'Amount (Br)',
  'withdraw.to': 'Send my money to',
  'withdraw.account.telebirr': 'Your Telebirr number',
  'withdraw.account.cbe': 'Your CBE account number',
  'withdraw.account.required': 'Enter the account to send it to.',
  'withdraw.account.invalid': "That number doesn't look right.",
  'withdraw.accountHint.telebirr': 'The phone number registered with Telebirr, like 0911 22 33 44.',
  'withdraw.accountHint.cbe': 'Your 13-digit CBE account number.',
  'withdraw.problem.required': 'Enter an amount.',
  'withdraw.problem.min': 'The smallest withdrawal is {min}.',
  'withdraw.problem.balance': 'That is more than your balance ({balance}).',
  'withdraw.note':
    "The amount leaves your balance right away. We send it to the account above after checking, usually within a day. If we can't, it goes back to your balance and we tell you why.",
  'withdraw.submit': 'Request withdrawal',
  'withdraw.confirmTitle': 'Send to this account?',
  'withdraw.confirmBody': 'Send {amount} to {provider} {account}? Check the number: money sent to a wrong number cannot be recovered.',
  'withdraw.confirm': 'Request it',
  'withdraw.doneTitle': 'Request sent',
  'withdraw.doneBody': '{amount} is on hold. We will send it to {provider} {account} soon.',

  'cart.payWallet': 'Paid instantly from your wallet ({balance} available).',
  'cart.payBank': "Your wallet ({balance}) doesn't cover this, so you'll pay by Telebirr or CBE next.",
  'cart.checkoutWallet': 'Pay {amount} from wallet',

  'pay.wallet': 'Pay {amount} from wallet',
  'pay.walletOr': 'Your wallet covers this order',
  'pay.walletFailed': "Couldn't pay from the wallet. Your balance may have changed. Nothing was taken.",
  'pay.discountApplied': 'Code applied: -{amount}',
} as const;

// Tournament screens' strings, spread into `en` / `am` below. The Amharic object must have every key (typed).
// Money-policy sentences (the fee split, what a cancellation does) stay English in Amharic until a native speaker
// approves them: they are listed in AM_NEEDS_REVIEW (strings.ts).

const TOURNAMENT_STRINGS_EN = {
  'tournament.title': 'Tournaments',
  'tournament.profileRow': 'Tournaments',
  'tournament.hostButton': 'Host a tournament',
  'tournament.tab.open': 'Open',
  'tournament.tab.hosting': 'Hosting',
  'tournament.filter.all': 'All games',
  'tournament.game.free_fire': 'Free Fire',
  'tournament.game.pubg_mobile': 'PUBG Mobile',
  'tournament.mode.battle_royale': 'Battle Royale',
  'tournament.mode.clash_squad': 'Clash Squad',
  'tournament.mode.lone_wolf': 'Lone Wolf',
  'tournament.mode.classic': 'Classic (Battle Royale)',
  'tournament.mode.tdm': 'Team Deathmatch',
  'tournament.kind.register': 'Register',
  'tournament.kind.live': 'Live',
  'tournament.phase.upcoming': 'Upcoming',
  'tournament.phase.started': 'Started',
  'tournament.phase.cancelled': 'Cancelled',
  'tournament.phase.finished': 'Finished',
  'tournament.in.day': 'in {n} d',
  'tournament.in.hour': 'in {n} h',
  'tournament.in.min': 'in {n} min',
  'tournament.teams': '{teams} teams of {size}',
  'tournament.teamsSolo': '{teams} players, solo',
  'tournament.players': '{n} players',
  'tournament.teamSizeOnly': 'Teams of {size}',
  'tournament.solo': 'Solo',
  'tournament.free': 'Free',
  'tournament.paid': 'Paid',
  'tournament.feePerTeam': '{amount} per team',
  'tournament.firstPlace': '1st place: {prize}',
  'tournament.prizeItems': '{n} items',
  'tournament.prizeItem': '1 item',
  'tournament.empty.open': 'No tournaments yet',
  'tournament.empty.openBody': 'When a creator hosts one, it shows up here.',
  'tournament.empty.hosting': "You haven't hosted a tournament yet",
  'tournament.empty.hostingBody': 'Tap "Host a tournament" to set one up.',

  // detail
  'tournament.detail.starts': 'Starts',
  'tournament.detail.format': 'Format',
  'tournament.detail.entry': 'Entry',
  'tournament.detail.host': 'Hosted by',
  'tournament.detail.watch': 'Watch',
  'tournament.detail.openStream': 'Open',
  'tournament.detail.rewards': 'Rewards',
  'tournament.detail.player': 'Player {n}',
  'tournament.detail.everyPlayer': 'Every player',
  'tournament.detail.notFound': "This tournament doesn't exist any more.",
  'tournament.detail.youHost': "You're hosting this",
  'tournament.detail.edit': 'Edit details',
  'tournament.detail.cancel': 'Cancel tournament',
  'tournament.detail.cancelTitle': 'Cancel this tournament?',
  'tournament.detail.cancelBody': "Everyone sees it as cancelled. This can't be undone.",
  'tournament.detail.cancelConfirm': 'Cancel it',
  'tournament.detail.keep': 'Keep it',
  'tournament.detail.cancelled': 'Tournament cancelled',
  'tournament.detail.saved': 'Saved',
  'tournament.detail.editTitle': 'Edit details',
  'tournament.detail.editNote': 'Only the name, start time and stream link can change once it is published.',
  'tournament.detail.liveNote': 'A live event: no sign-up. Watch the stream at the start time.',
  'tournament.detail.rewardsNote': 'Paid for by the host and kept safe until the winners are picked.',
  'tournament.place.1': '1st place',
  'tournament.place.2': '2nd place',
  'tournament.place.3': '3rd place',
  'tournament.place.n': '{n}th place',

  // stream platforms
  'tournament.platform.tiktok': 'TikTok',
  'tournament.platform.youtube': 'YouTube',
  'tournament.platform.twitch': 'Twitch',
  'tournament.platform.facebook': 'Facebook',
  'tournament.platform.instagram': 'Instagram',
  'tournament.platform.kick': 'Kick',
  'tournament.platform.other': 'Stream',

  // host wizard
  'tournament.host.title': 'Host a tournament',
  'tournament.host.step': 'Step {n} of {total}',
  'tournament.host.next': 'Next',
  'tournament.host.back': 'Back',
  'tournament.host.gameTitle': 'Choose the game',
  'tournament.host.kindTitle': 'What kind of tournament?',
  'tournament.host.kind.registerBody': 'Teams sign up in the app before it starts. Free or with an entry fee.',
  'tournament.host.kind.liveBody': 'A live event you stream. People get a reminder and the room ID in the app. No sign-up.',
  'tournament.host.detailsTitle': 'Details',
  'tournament.host.name': 'Tournament name',
  'tournament.host.namePlaceholder': 'e.g. Friday Night Cup',
  'tournament.host.mode': 'Mode',
  'tournament.host.teamSize': 'Players per team',
  'tournament.host.playerCount': 'Players in the tournament',
  'tournament.host.split': '{teams} teams × {size} players = {players} players',
  'tournament.host.splitSolo': '{players} players, each on their own',
  'tournament.host.entry': 'Entry',
  'tournament.host.fee': 'Entry fee, per team (birr)',
  'tournament.host.feeNote': 'The team captain pays once for the whole team. You get 85% of each fee when the tournament ends (the platform keeps 15%). If you cancel, every team gets its fee back.',
  'tournament.host.feeYouGet': 'You get {amount} per team',
  'tournament.host.startsAt': 'Date and time it starts',
  'tournament.host.pickTime': 'Pick a date and time',
  'tournament.host.stream': 'Stream link (TikTok, YouTube...)',
  'tournament.host.streamOptional': 'Stream link (optional)',
  'tournament.host.streamPlaceholder': 'tiktok.com/@yourname',
  'tournament.host.streamDetected': 'Opens on {platform}',
  'tournament.host.rewardsTitle': 'Rewards',
  'tournament.host.rewardsBody': 'Choose what each player of each winning team gets. You pay for them when you publish; they are kept safe until you pick the winners.',
  'tournament.host.places': 'Winning places',
  'tournament.host.chooseReward': 'Choose reward',
  'tournament.host.totals': 'Rewards total: {money}',
  'tournament.host.totalsWithItems': 'Rewards total: {money} + {n} items ({price} today)',
  'tournament.host.reviewTitle': 'Check and publish',
  'tournament.host.publish': 'Publish',
  'tournament.host.publishTitle': 'Publish this tournament?',
  'tournament.host.publishBody': 'Everyone can see it right away. After this only the name, start time and stream link can change.',
  'tournament.host.published': 'Tournament published',
  'tournament.host.prize': 'What the winner gets',
  'tournament.host.prizePlaceholder': 'e.g. 1,000 diamonds for the winning squad',
  'tournament.host.payNow': 'You pay {amount} now.',
  'tournament.host.payNote': 'The rewards are paid when you publish and kept safe for the winners. If you cancel, it all comes back to your wallet.',
  'tournament.host.yourBalance': 'Your balance: {amount}',
  'tournament.host.payAndPublish': 'Pay and publish',
  'tournament.err.prize': 'Say what the winner gets (2 to 300 characters).',
  'tournament.err.insufficient_balance': "Your balance doesn't cover the rewards. Top up, then publish.",

  // reward editor
  'tournament.reward.title': '{place} · Player {n}',
  'tournament.reward.money': 'Money',
  'tournament.reward.product': 'Game product',
  'tournament.reward.amount': 'Amount (birr)',
  'tournament.reward.search': 'Search products',
  'tournament.reward.noPacks': 'No products match.',
  'tournament.reward.save': 'Save',
  'tournament.reward.saveAll': 'Save for every player in {place}',
  'tournament.reward.remove': 'Remove',

  // form problems
  'tournament.err.game': 'Choose a game.',
  'tournament.err.kind': 'Choose the kind of tournament.',
  'tournament.err.mode': 'Choose a mode.',
  'tournament.err.name': 'Give it a name of 3 to 60 characters.',
  'tournament.err.teamSize': 'Choose how many players are in a team.',
  'tournament.err.teamCount': 'Choose how many players can take part.',
  'tournament.err.fee': 'Type the entry fee in birr (for example 50).',
  'tournament.err.startMissing': 'Pick the date and time it starts.',
  'tournament.err.startTooSoon': 'It has to start at least 15 minutes from now.',
  'tournament.err.startTooFar': 'It has to start within the next 90 days.',
  'tournament.err.streamRequired': 'A live tournament needs the stream link.',
  'tournament.err.streamInvalid': 'That stream link doesn\'t look right. Paste the full https:// link.',
  'tournament.err.rewards': 'Choose a reward for every player of every winning place.',
  'tournament.err.amount': 'Type an amount in birr, more than 0.',
  'tournament.err.not_a_creator': 'Only content creators can host tournaments.',
  'tournament.err.reward_pack_unavailable': 'One of the reward products is no longer on sale. Choose another.',
  'tournament.err.too_many_tournaments': 'You can have at most 10 upcoming tournaments.',
  'tournament.err.tournament_closed': 'This tournament has already started or ended.',
  'tournament.err.generic': "Couldn't save. Check your connection and try again.",
  'tournament.phase.unpaid': 'Awaiting payment',
  'tournament.openPayment': 'Continue to payment',
  'tournament.err.pendingOrder': 'You have an unpaid order. Finish or cancel it first.',
  'tournament.host.payByBank': "Your wallet doesn't cover it, so you'll pay with Telebirr or CBE next. The tournament is published as soon as the payment is confirmed.",
  'tournament.host.payByWallet': 'It is paid from your wallet balance.',
  'tournament.team.paying': "A payment for this team has started. Finish it to register; the team can't be changed until then.",
  'tournament.team.payByBank': "Your wallet doesn't cover the fee, so you'll pay with Telebirr or CBE next. The team is registered as soon as the payment is confirmed.",
  'tournament.team.payByWallet': 'The fee is paid from your wallet balance.',
  'tournament.detail.finishPayment': 'Finish payment',
  'tournament.detail.awaitingPayment': 'Only you can see this until the rewards payment is confirmed. Then it is published.',
  'tournament.pay.open': 'Open tournament',
  'tournament.pay.refunded': "The payment was confirmed, but it couldn't be used (the tournament filled up or starts too soon). The money is back in your wallet.",
  'tournament.tab.mine': 'Joined',
  'tournament.empty.mine': "You haven't joined a tournament yet",
  'tournament.empty.mineBody': 'Teams you register and tournaments you asked to be reminded of show up here.',
  'tournament.detail.register': 'Register a team',
  'tournament.detail.continueDraft': 'Continue your team',
  'tournament.detail.yourTeam': 'Your team: {name}',
  'tournament.detail.full': 'All spots are taken',
  'tournament.detail.spots': '{n} of {total} teams registered',
  'tournament.detail.teams': 'Teams',
  'tournament.detail.noTeams': 'No team has registered yet.',
  'tournament.detail.remind': 'Remind me',
  'tournament.detail.reminded': "We'll remind you",
  'tournament.detail.remindHint': 'You get a notification 15 minutes before it starts.',
  'tournament.detail.closed': 'Registration is closed.',
  'tournament.team.title': 'Your team',
  'tournament.team.hint': 'Add each player with the email they use in this app, then check their game ID. Save a draft anytime.',
  'tournament.team.name': 'Team name',
  'tournament.team.namePlaceholder': 'e.g. Addis Wolves',
  'tournament.team.captain': 'Player 1 · You (captain)',
  'tournament.team.email': 'Their app email',
  'tournament.team.find': 'Find',
  'tournament.team.change': 'Change',
  'tournament.team.check': 'Check',
  'tournament.team.checked': 'In game: {name}',
  'tournament.team.checkedNoName': 'ID checked',
  'tournament.team.invalid': "That ID wasn't found in the game.",
  'tournament.team.unavailable': "Couldn't check right now. Try again.",
  'tournament.team.busy': 'Too many checks. Wait a minute, then try again.',
  'tournament.team.notFound': 'No account uses that email.',
  'tournament.team.self': "That's you. You're player 1.",
  'tournament.team.tooMany': 'Too many searches. Wait a few minutes.',
  'tournament.team.lookupError': "Couldn't search right now. Try again.",
  'tournament.team.save': 'Save draft',
  'tournament.team.saved': 'Draft saved',
  'tournament.team.register': 'Register team',
  'tournament.team.registerPay': 'Pay {amount} and register',
  'tournament.team.confirmTitle': 'Register this team?',
  'tournament.team.confirmBody': 'The {amount} entry fee is paid from your wallet now and held until the tournament ends. If the tournament is cancelled, you get it back.',
  'tournament.team.confirmFree': 'Your team takes a spot, and every player is told they were added.',
  'tournament.team.registered': 'Team registered!',
  'tournament.team.registeredBadge': 'Registered',
  'tournament.team.draftBadge': 'Draft',
  'tournament.team.discard': 'Delete draft',
  'tournament.team.discardTitle': 'Delete this draft?',
  'tournament.team.discardBody': 'Nothing was paid. The team details are removed.',
  'tournament.team.feePaid': 'Entry fee paid: {amount}',
  'tournament.team.noCheck': "Game IDs can't be checked for this game right now, so teams can't register yet. Try again later.",
  'tournament.team.err.teamName': 'Give your team a name (2 to 30 characters).',
  'tournament.team.err.teamIncomplete': 'Add every player and check each game ID first.',
  'tournament.team.err.duplicateGameId': 'Two players have the same game ID.',
  'tournament.team.err.duplicatePlayer': 'The same person is in the team twice.',
  'tournament.team.err.team_name_taken': 'Another team already has that name.',
  'tournament.team.err.already_in_team': 'One of these players is already in another team.',
  'tournament.team.err.tournament_full': 'Sorry, the tournament is full.',
  'tournament.team.err.tournament_closed': 'Registration is closed.',
  'tournament.team.err.id_not_verified': 'A game ID needs checking again. Tap Check next to it.',
  'tournament.team.err.insufficient_balance': "Your balance doesn't cover the entry fee. Top up first.",
  'tournament.team.err.host_cannot_join': "The host can't play in their own tournament.",
  'tournament.team.err.generic': "Couldn't save. Check your connection and try again.",
  'tournament.host.prizeEdit': 'What the winner gets',
} as const;

type TournamentStringKey = keyof typeof TOURNAMENT_STRINGS_EN;

const TOURNAMENT_STRINGS_AM: Record<TournamentStringKey, string> = {
  'tournament.title': 'ውድድሮች',
  'tournament.profileRow': 'ውድድሮች',
  'tournament.hostButton': 'ውድድር አዘጋጅ',
  'tournament.tab.open': 'ክፍት',
  'tournament.tab.hosting': 'ያዘጋጀሁት',
  'tournament.filter.all': 'ሁሉም ጨዋታዎች',
  'tournament.game.free_fire': 'Free Fire',
  'tournament.game.pubg_mobile': 'PUBG Mobile',
  'tournament.mode.battle_royale': 'Battle Royale',
  'tournament.mode.clash_squad': 'Clash Squad',
  'tournament.mode.lone_wolf': 'Lone Wolf',
  'tournament.mode.classic': 'Classic (Battle Royale)',
  'tournament.mode.tdm': 'Team Deathmatch',
  'tournament.kind.register': 'በምዝገባ',
  'tournament.kind.live': 'ቀጥታ',
  'tournament.phase.upcoming': 'የሚመጣ',
  'tournament.phase.started': 'ተጀምሯል',
  'tournament.phase.cancelled': 'ተሰርዟል',
  'tournament.phase.finished': 'አልቋል',
  'tournament.in.day': 'በ{n} ቀን',
  'tournament.in.hour': 'በ{n} ሰዓት',
  'tournament.in.min': 'በ{n} ደቂቃ',
  'tournament.teams': '{teams} ቡድኖች፣ እያንዳንዳቸው {size}',
  'tournament.teamsSolo': '{teams} ተጫዋቾች፣ በግል',
  'tournament.players': '{n} ተጫዋቾች',
  'tournament.teamSizeOnly': 'ቡድን {size}',
  'tournament.solo': 'በግል',
  'tournament.free': 'ነፃ',
  'tournament.paid': 'የሚከፈልበት',
  'tournament.feePerTeam': 'ለአንድ ቡድን {amount}',
  'tournament.firstPlace': '1ኛ ደረጃ፦ {prize}',
  'tournament.prizeItems': '{n} ዕቃዎች',
  'tournament.prizeItem': '1 ዕቃ',
  'tournament.empty.open': 'እስካሁን ውድድር የለም',
  'tournament.empty.openBody': 'አንድ ፈጣሪ ሲያዘጋጅ እዚህ ይታያል።',
  'tournament.empty.hosting': 'እስካሁን ውድድር አላዘጋጁም',
  'tournament.empty.hostingBody': 'ለማዘጋጀት "ውድድር አዘጋጅ" ይንኩ።',

  'tournament.detail.starts': 'የሚጀምረው',
  'tournament.detail.format': 'አደረጃጀት',
  'tournament.detail.entry': 'መግቢያ',
  'tournament.detail.host': 'አዘጋጅ',
  'tournament.detail.watch': 'ይመልከቱ',
  'tournament.detail.openStream': 'ክፈት',
  'tournament.detail.rewards': 'ሽልማቶች',
  'tournament.detail.player': 'ተጫዋች {n}',
  'tournament.detail.everyPlayer': 'ለእያንዳንዱ ተጫዋች',
  'tournament.detail.notFound': 'ይህ ውድድር ከእንግዲህ የለም።',
  'tournament.detail.youHost': 'ይህን እርስዎ ነዎት ያዘጋጁት',
  'tournament.detail.edit': 'ዝርዝሩን አስተካክል',
  'tournament.detail.cancel': 'ውድድሩን ሰርዝ',
  'tournament.detail.cancelTitle': 'ይህን ውድድር ይሰርዙ?',
  'tournament.detail.cancelBody': "Everyone sees it as cancelled. This can't be undone.",
  'tournament.detail.cancelConfirm': 'ሰርዝ',
  'tournament.detail.keep': 'ይቆይ',
  'tournament.detail.cancelled': 'ውድድሩ ተሰርዟል',
  'tournament.detail.saved': 'ተቀምጧል',
  'tournament.detail.editTitle': 'ዝርዝሩን አስተካክል',
  'tournament.detail.editNote': 'ከታተመ በኋላ ስሙ፣ የመጀመሪያ ሰዓቱ እና የቀጥታ ስርጭት ሊንኩ ብቻ ነው የሚቀየረው።',
  'tournament.detail.liveNote': 'ቀጥታ ዝግጅት ነው፤ ምዝገባ የለም። በተያዘው ሰዓት ስርጭቱን ይመልከቱ።',
  'tournament.detail.rewardsNote': 'Paid for by the host and kept safe until the winners are picked.',
  'tournament.place.1': '1ኛ ደረጃ',
  'tournament.place.2': '2ኛ ደረጃ',
  'tournament.place.3': '3ኛ ደረጃ',
  'tournament.place.n': '{n}ኛ ደረጃ',

  'tournament.platform.tiktok': 'TikTok',
  'tournament.platform.youtube': 'YouTube',
  'tournament.platform.twitch': 'Twitch',
  'tournament.platform.facebook': 'Facebook',
  'tournament.platform.instagram': 'Instagram',
  'tournament.platform.kick': 'Kick',
  'tournament.platform.other': 'ስርጭት',

  'tournament.host.title': 'ውድድር አዘጋጅ',
  'tournament.host.step': 'ደረጃ {n} ከ{total}',
  'tournament.host.next': 'ቀጥል',
  'tournament.host.back': 'ተመለስ',
  'tournament.host.gameTitle': 'ጨዋታውን ይምረጡ',
  'tournament.host.kindTitle': 'ምን አይነት ውድድር?',
  'tournament.host.kind.registerBody': 'ቡድኖች ከመጀመሩ በፊት በመተግበሪያው ይመዘገባሉ። በነፃ ወይም በመግቢያ ክፍያ።',
  'tournament.host.kind.liveBody': 'እርስዎ በቀጥታ የሚያሰራጩት ዝግጅት። ሰዎች ማስታወሻ እና የክፍሉን መለያ በመተግበሪያው ያገኛሉ። ምዝገባ የለም።',
  'tournament.host.detailsTitle': 'ዝርዝሮች',
  'tournament.host.name': 'የውድድሩ ስም',
  'tournament.host.namePlaceholder': 'ለምሳሌ የአርብ ምሽት ዋንጫ',
  'tournament.host.mode': 'የጨዋታ አይነት',
  'tournament.host.teamSize': 'በአንድ ቡድን ስንት ተጫዋች',
  'tournament.host.playerCount': 'በውድድሩ ስንት ተጫዋች',
  'tournament.host.split': '{teams} ቡድኖች × {size} ተጫዋቾች = {players} ተጫዋቾች',
  'tournament.host.splitSolo': '{players} ተጫዋቾች፣ እያንዳንዳቸው በግል',
  'tournament.host.entry': 'መግቢያ',
  'tournament.host.fee': 'የመግቢያ ክፍያ፣ ለአንድ ቡድን (ብር)',
  'tournament.host.feeNote':
    'The team captain pays once for the whole team. You get 85% of each fee when the tournament ends (the platform keeps 15%). If you cancel, every team gets its fee back.',
  'tournament.host.feeYouGet': 'You get {amount} per team',
  'tournament.host.startsAt': 'የሚጀምርበት ቀን እና ሰዓት',
  'tournament.host.pickTime': 'ቀን እና ሰዓት ይምረጡ',
  'tournament.host.stream': 'የስርጭት ሊንክ (TikTok፣ YouTube...)',
  'tournament.host.streamOptional': 'የስርጭት ሊንክ (አማራጭ)',
  'tournament.host.streamPlaceholder': 'tiktok.com/@yourname',
  'tournament.host.streamDetected': 'በ{platform} ይከፈታል',
  'tournament.host.rewardsTitle': 'ሽልማቶች',
  'tournament.host.rewardsBody': 'ለእያንዳንዱ አሸናፊ ቡድን እያንዳንዱ ተጫዋች ምን እንደሚያገኝ ይምረጡ። ሲያትሙ ይከፍላሉ፤ አሸናፊዎችን እስኪመርጡ ድረስ በጥንቃቄ ይቀመጣል።',
  'tournament.host.places': 'የሚሸለሙ ደረጃዎች',
  'tournament.host.chooseReward': 'ሽልማት ይምረጡ',
  'tournament.host.totals': 'Rewards total: {money}',
  'tournament.host.totalsWithItems': 'Rewards total: {money} + {n} items ({price} today)',
  'tournament.host.reviewTitle': 'ያረጋግጡ እና ያትሙ',
  'tournament.host.publish': 'አትም',
  'tournament.host.publishTitle': 'ይህን ውድድር ያትሙ?',
  'tournament.host.publishBody': 'ሁሉም ወዲያውኑ ያዩታል። ከዚህ በኋላ ስሙ፣ የመጀመሪያ ሰዓቱ እና የስርጭት ሊንኩ ብቻ ነው የሚቀየረው።',
  'tournament.host.published': 'ውድድሩ ታትሟል',
  'tournament.host.prize': 'አሸናፊው የሚያገኘው',
  'tournament.host.prizePlaceholder': 'ለምሳሌ ለአሸናፊው ቡድን 1,000 ዳይመንድ',
  'tournament.host.payNow': 'You pay {amount} now.',
  'tournament.host.payNote': 'The rewards are paid when you publish and kept safe for the winners. If you cancel, it all comes back to your wallet.',
  'tournament.host.yourBalance': 'ቀሪ ሂሳብዎ፦ {amount}',
  'tournament.host.payAndPublish': 'Pay and publish',
  'tournament.err.prize': 'አሸናፊው ምን እንደሚያገኝ ይጻፉ (ከ2 እስከ 300 ፊደል)።',
  'tournament.err.insufficient_balance': "Your balance doesn't cover the rewards. Top up, then publish.",

  'tournament.reward.title': '{place} · ተጫዋች {n}',
  'tournament.reward.money': 'ገንዘብ',
  'tournament.reward.product': 'የጨዋታ ምርት',
  'tournament.reward.amount': 'መጠን (ብር)',
  'tournament.reward.search': 'ምርቶችን ይፈልጉ',
  'tournament.reward.noPacks': 'የሚመሳሰል ምርት የለም።',
  'tournament.reward.save': 'አስቀምጥ',
  'tournament.reward.saveAll': 'ለ{place} ተጫዋቾች በሙሉ አስቀምጥ',
  'tournament.reward.remove': 'አስወግድ',

  'tournament.err.game': 'ጨዋታ ይምረጡ።',
  'tournament.err.kind': 'የውድድሩን አይነት ይምረጡ።',
  'tournament.err.mode': 'የጨዋታ አይነት ይምረጡ።',
  'tournament.err.name': 'ከ3 እስከ 60 ፊደል ያለው ስም ይስጡት።',
  'tournament.err.teamSize': 'በአንድ ቡድን ስንት ተጫዋች እንዳለ ይምረጡ።',
  'tournament.err.teamCount': 'ስንት ተጫዋች መሳተፍ እንደሚችል ይምረጡ።',
  'tournament.err.fee': 'የመግቢያ ክፍያውን በብር ይጻፉ (ለምሳሌ 50)።',
  'tournament.err.startMissing': 'የሚጀምርበትን ቀን እና ሰዓት ይምረጡ።',
  'tournament.err.startTooSoon': 'ቢያንስ ከአሁን 15 ደቂቃ በኋላ መጀመር አለበት።',
  'tournament.err.startTooFar': 'በሚቀጥሉት 90 ቀናት ውስጥ መጀመር አለበት።',
  'tournament.err.streamRequired': 'ቀጥታ ውድድር የስርጭት ሊንክ ያስፈልገዋል።',
  'tournament.err.streamInvalid': 'ይህ የስርጭት ሊንክ ትክክል አይመስልም። ሙሉውን https:// ሊንክ ይለጥፉ።',
  'tournament.err.rewards': 'ለእያንዳንዱ የሚሸለም ደረጃ ለእያንዳንዱ ተጫዋች ሽልማት ይምረጡ።',
  'tournament.err.amount': 'ከ0 በላይ የሆነ መጠን በብር ይጻፉ።',
  'tournament.err.not_a_creator': 'ውድድር ማዘጋጀት የሚችሉት የይዘት ፈጣሪዎች ብቻ ናቸው።',
  'tournament.err.reward_pack_unavailable': 'ከሽልማት ምርቶቹ አንዱ ከእንግዲህ አይሸጥም። ሌላ ይምረጡ።',
  'tournament.err.too_many_tournaments': 'ቢበዛ 10 የሚመጡ ውድድሮች ብቻ ሊኖርዎት ይችላል።',
  'tournament.err.tournament_closed': 'ይህ ውድድር ተጀምሯል ወይም አልቋል።',
  'tournament.err.generic': 'ማስቀመጥ አልተቻለም። ግንኙነትዎን አረጋግጠው እንደገና ይሞክሩ።',
  'tournament.phase.unpaid': 'ክፍያ በመጠባበቅ ላይ',
  'tournament.openPayment': 'ወደ ክፍያ ይቀጥሉ',
  'tournament.err.pendingOrder': 'You have an unpaid order. Finish or cancel it first.',
  'tournament.host.payByBank': "Your wallet doesn't cover it, so you'll pay with Telebirr or CBE next. The tournament is published as soon as the payment is confirmed.",
  'tournament.host.payByWallet': 'It is paid from your wallet balance.',
  'tournament.team.paying': "A payment for this team has started. Finish it to register; the team can't be changed until then.",
  'tournament.team.payByBank': "Your wallet doesn't cover the fee, so you'll pay with Telebirr or CBE next. The team is registered as soon as the payment is confirmed.",
  'tournament.team.payByWallet': 'The fee is paid from your wallet balance.',
  'tournament.detail.finishPayment': 'ክፍያውን ይጨርሱ',
  'tournament.detail.awaitingPayment': 'Only you can see this until the rewards payment is confirmed. Then it is published.',
  'tournament.pay.open': 'ውድድሩን ክፈት',
  'tournament.pay.refunded': "The payment was confirmed, but it couldn't be used (the tournament filled up or starts too soon). The money is back in your wallet.",
  'tournament.tab.mine': 'የተቀላቀልኩት',
  'tournament.empty.mine': 'እስካሁን ምንም ውድድር አልተቀላቀሉም',
  'tournament.empty.mineBody': 'የሚያስመዘግቧቸው ቡድኖች እና እንዲያስታውሱዎት የጠየቋቸው ውድድሮች እዚህ ይታያሉ።',
  'tournament.detail.register': 'ቡድን አስመዝግብ',
  'tournament.detail.continueDraft': 'ቡድንዎን ይቀጥሉ',
  'tournament.detail.yourTeam': 'ቡድንዎ፦ {name}',
  'tournament.detail.full': 'ሁሉም ቦታዎች ተይዘዋል',
  'tournament.detail.spots': '{n} ከ{total} ቡድኖች ተመዝግበዋል',
  'tournament.detail.teams': 'ቡድኖች',
  'tournament.detail.noTeams': 'እስካሁን የተመዘገበ ቡድን የለም።',
  'tournament.detail.remind': 'አስታውሰኝ',
  'tournament.detail.reminded': 'እናስታውስዎታለን',
  'tournament.detail.remindHint': 'ከመጀመሩ 15 ደቂቃ በፊት ማሳወቂያ ያገኛሉ።',
  'tournament.detail.closed': 'ምዝገባው ተዘግቷል።',
  'tournament.team.title': 'ቡድንዎ',
  'tournament.team.hint': 'እያንዳንዱን ተጫዋች በዚህ መተግበሪያ በሚጠቀሙበት ኢሜል ያክሉ፣ ከዚያ የጨዋታ መለያቸውን ያረጋግጡ። በማንኛውም ጊዜ ረቂቅ ማስቀመጥ ይችላሉ።',
  'tournament.team.name': 'የቡድን ስም',
  'tournament.team.namePlaceholder': 'ለምሳሌ የአዲስ ተኩላዎች',
  'tournament.team.captain': 'ተጫዋች 1 · እርስዎ (ካፒቴን)',
  'tournament.team.email': 'የመተግበሪያ ኢሜላቸው',
  'tournament.team.find': 'ፈልግ',
  'tournament.team.change': 'ቀይር',
  'tournament.team.check': 'አረጋግጥ',
  'tournament.team.checked': 'በጨዋታው ውስጥ፦ {name}',
  'tournament.team.checkedNoName': 'መለያው ተረጋግጧል',
  'tournament.team.invalid': 'ይህ መለያ በጨዋታው ውስጥ አልተገኘም።',
  'tournament.team.unavailable': 'አሁን ማረጋገጥ አልተቻለም። እንደገና ይሞክሩ።',
  'tournament.team.busy': 'በጣም ብዙ ማረጋገጫዎች። አንድ ደቂቃ ቆይተው እንደገና ይሞክሩ።',
  'tournament.team.notFound': 'ይህን ኢሜል የሚጠቀም መለያ የለም።',
  'tournament.team.self': 'ያ እርስዎ ነዎት። እርስዎ ተጫዋች 1 ነዎት።',
  'tournament.team.tooMany': 'በጣም ብዙ ፍለጋዎች። ጥቂት ደቂቃዎች ይጠብቁ።',
  'tournament.team.lookupError': 'አሁን መፈለግ አልተቻለም። እንደገና ይሞክሩ።',
  'tournament.team.save': 'ረቂቁን አስቀምጥ',
  'tournament.team.saved': 'ረቂቁ ተቀምጧል',
  'tournament.team.register': 'ቡድኑን አስመዝግብ',
  'tournament.team.registerPay': 'Pay {amount} and register',
  'tournament.team.confirmTitle': 'ይህን ቡድን ያስመዝግቡ?',
  'tournament.team.confirmBody': 'The {amount} entry fee is paid from your wallet now and held until the tournament ends. If the tournament is cancelled, you get it back.',
  'tournament.team.confirmFree': 'ቡድንዎ ቦታ ይይዛል፤ እያንዳንዱ ተጫዋችም መጨመሩ ይነገረዋል።',
  'tournament.team.registered': 'ቡድኑ ተመዝግቧል!',
  'tournament.team.registeredBadge': 'ተመዝግቧል',
  'tournament.team.draftBadge': 'ረቂቅ',
  'tournament.team.discard': 'ረቂቁን ሰርዝ',
  'tournament.team.discardTitle': 'ይህን ረቂቅ ይሰርዙ?',
  'tournament.team.discardBody': 'ምንም አልተከፈለም። የቡድኑ ዝርዝር ይሰረዛል።',
  'tournament.team.feePaid': 'Entry fee paid: {amount}',
  'tournament.team.noCheck': 'ለዚህ ጨዋታ የጨዋታ መለያዎች አሁን ሊረጋገጡ አይችሉም፤ ስለዚህ ቡድኖች ገና መመዝገብ አይችሉም። ቆይተው ይሞክሩ።',
  'tournament.team.err.teamName': 'ለቡድንዎ ስም ይስጡ (ከ2 እስከ 30 ፊደል)።',
  'tournament.team.err.teamIncomplete': 'መጀመሪያ ሁሉንም ተጫዋቾች ያክሉ እና የእያንዳንዳቸውን የጨዋታ መለያ ያረጋግጡ።',
  'tournament.team.err.duplicateGameId': 'ሁለት ተጫዋቾች አንድ አይነት የጨዋታ መለያ አላቸው።',
  'tournament.team.err.duplicatePlayer': 'አንድ ሰው በቡድኑ ውስጥ ሁለት ጊዜ አለ።',
  'tournament.team.err.team_name_taken': 'ሌላ ቡድን ይህን ስም ይዟል።',
  'tournament.team.err.already_in_team': 'ከእነዚህ ተጫዋቾች አንዱ ቀድሞውኑ በሌላ ቡድን ውስጥ ነው።',
  'tournament.team.err.tournament_full': 'ይቅርታ፣ ውድድሩ ሞልቷል።',
  'tournament.team.err.tournament_closed': 'ምዝገባው ተዘግቷል።',
  'tournament.team.err.id_not_verified': 'አንድ የጨዋታ መለያ እንደገና መረጋገጥ አለበት። ከጎኑ ያለውን አረጋግጥ ይንኩ።',
  'tournament.team.err.insufficient_balance': "Your balance doesn't cover the entry fee. Top up first.",
  'tournament.team.err.host_cannot_join': 'አዘጋጁ በራሱ ውድድር መጫወት አይችልም።',
  'tournament.team.err.generic': 'ማስቀመጥ አልተቻለም። ግንኙነትዎን አረጋግጠው እንደገና ይሞክሩ።',
  'tournament.host.prizeEdit': 'አሸናፊው የሚያገኘው',
};

/** Kept English in Amharic on purpose (money policy); listed in AM_NEEDS_REVIEW. */
const TOURNAMENT_AM_NEEDS_REVIEW = [
  'tournament.detail.cancelBody',
  'tournament.detail.rewardsNote',
  'tournament.host.feeNote',
  'tournament.host.feeYouGet',
  'tournament.host.totals',
  'tournament.host.totalsWithItems',
  'tournament.host.payNow',
  'tournament.host.payNote',
  'tournament.host.payAndPublish',
  'tournament.err.insufficient_balance',
  'tournament.team.registerPay',
  'tournament.team.confirmBody',
  'tournament.team.feePaid',
  'tournament.team.err.insufficient_balance',
  'tournament.err.pendingOrder',
  'tournament.host.payByBank',
  'tournament.host.payByWallet',
  'tournament.team.paying',
  'tournament.team.payByBank',
  'tournament.team.payByWallet',
  'tournament.detail.awaitingPayment',
  'tournament.pay.refunded',
] as const satisfies readonly TournamentStringKey[];

export const en = {
  // tabs
  'tab.shop': 'Shop',
  'tab.orders': 'Orders',
  'tab.vault': 'Vault',
  'tab.profile': 'Profile',

  // accessibility hints for the tab dots
  'a11y.openOrders': '{n} open orders',
  'a11y.newCodes': '{n} new codes',

  // common
  'common.balance': 'Balance',
  'common.retry': 'Try again',
  'common.cancel': 'Cancel',
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.loadError': "Couldn't load this. Check your connection, then try again.",
  'common.topUp': 'Top up',

  // time
  'time.now': 'just now',
  'time.min': '{n}m ago',
  'time.hour': '{n}h ago',
  'time.day': '{n}d ago',

  // shop
  'shop.search': 'Search games, gift cards, keys',
  'shop.buyAgain': 'Buy again',
  'shop.loading': 'Loading products',
  'shop.seeAll': 'See all',
  'shop.seeAllIn': 'See all {name}',
  'shop.results': 'Results',
  'shop.noResults': 'No results for “{q}”',
  'shop.noResultsBody': 'Check the spelling, or search for a different game or gift card.',
  'shop.clear': 'Clear search',
  'shop.emptyTitle': 'Nothing here yet',
  'shop.emptyBody': 'New products show up here as soon as they are available.',
  'shop.errorTitle': "Couldn't load products",
  'shop.addBalance': "Adding balance isn't available yet.",
  'cat.gift-cards': 'Gift cards',
  'cat.game-keys': 'Game keys',
  'cat.games': 'Games',
  'cat.subscriptions': 'Subscriptions',

  // product / checkout
  'product.choose': 'Choose an amount',
  'product.gameId': 'Game ID',
  'product.gameIdHint': 'Enter your player ID exactly as it shows in the game.',
  'product.paste': 'Paste',
  'product.pay': 'Pay {price}',
  'product.yourBalance': 'Your balance',
  'product.notEnough': 'Not enough balance',
  'product.placed': 'Order placed',
  'product.placedTopup': "We'll deliver it to your game ID shortly.",
  'product.placedCode': "Your code will appear in the Vault as soon as it's ready.",
  'product.viewOrder': 'View order',
  'product.backToShop': 'Back to shop',
  'product.notFound': 'This product is no longer available.',
  'product.codeNote': 'You get a code. It is delivered to your Vault.',
  'product.topupNote': 'Delivered straight to your game ID.',
  'product.region': 'Region',
  'product.idTitle': 'Your player ID',
  'product.checking': 'Checking…',
  'product.playerRegion': 'Account region: {region}',
  'product.playerLabel': 'Player: {name}',
  'product.retry': 'Retry',
  'product.checkAgain': 'Check again',
  'product.check.invalid': "We couldn't find that player ID. Check it and try again.",
  'product.check.failed': "Couldn't check the ID right now.",
  'product.check.timeout': 'Checking is taking too long.',
  'product.check.expired': 'This check has expired. Check the ID again.',
  'product.regionAuto': 'Selected {region} to match your account.',
  'product.regionWrong': "Your account is in region {account}. Packs in {region} won't work for it.",
  'product.regionSwitch': 'Switch to {region}',
  'product.regionNone': "We don't sell this for accounts in region {account}.",
  'product.regionUnknown': "We couldn't confirm your account's region, so we can't sell region-specific packs for it.",
  'product.packWrongRegion': "Not for your account's region",
  'product.packUnknownRegion': "Region couldn't be confirmed",
  'product.packUnavailable': 'Not available',
  'product.tick': "I've checked my ID is correct. Top-ups can't be reversed.",
  'product.total': 'Total',
  'product.continue': 'Continue',
  'product.was': 'was {price}',
  'product.off': '{pct}% off',
  'product.blocker.choose': 'Choose a pack',
  'product.blocker.fill': 'Enter your ID',
  'product.blocker.checking': 'Checking your ID…',
  'product.blocker.invalid': 'Fix your ID to continue',
  'product.blocker.failed': 'Retry the ID check to continue',
  'product.blocker.expired': 'Check your ID again to continue',
  'product.blocker.confirm': 'Tick the box to continue',
  'product.blocker.wrongRegion': "Pick a pack for your account's region",
  'product.blocker.regionUnknown': "This pack can't be sold for your account",
  'product.blocker.unavailable': 'This pack is not available',
  'product.confirmTitle': 'Confirm your order',
  'product.item': 'Pack',
  'product.player': 'Player',
  'product.price': 'Price',
  'product.balanceAfter': 'Balance after',
  'product.confirmPay': 'Confirm and pay {price}',
  'product.cancel': 'Cancel',
  'product.verifying': 'Checking the latest price…',

  // errors
  'err.insufficient': 'Not enough balance. Top up and try again.',
  'err.unavailable': 'This item is no longer available.',
  'err.accountId': 'Enter a valid game ID.',
  'err.generic': 'Something went wrong. Please try again.',
  'err.packageGone': 'That package is no longer available.',
  'err.priceChanged': 'The price changed from {old} to {now}. Review it and continue when ready.',
  'err.idNotValidated': 'We need to check your ID again.',
  'err.idExpired': 'Your ID check expired. Check it again.',
  'err.idCheckRequired': 'Tick the box to confirm your ID.',
  'err.regionMismatch': "This pack isn't available for your account's region ({region}).",
  'err.regionUnverified': "We couldn't confirm your account's region, so this pack can't be bought.",

  // orders
  'orders.title': 'Orders',
  'orders.emptyTitle': 'No orders yet',
  'orders.emptyBody': 'Your purchases show up here.',
  'orders.detail': 'Order details',
  'order.item': 'Item',
  'order.amount': 'Amount',
  'order.placed': 'Placed',
  'order.gameId': 'Game ID',
  'order.region': 'Region',
  'order.verified': 'ID checked with the game before ordering',
  'order.verifiedPlayer': 'Player: {name}',
  'order.verifiedRegion': 'Account region: {region}',
  'order.selfDeclared': 'You confirmed this ID yourself',
  'order.number': 'Order',
  'order.viewVault': 'View in Vault',
  'order.note.pending': "We've received your order and will start on it soon.",
  'order.note.processing': "We're working on your order right now.",
  'order.note.completedTopup': 'Delivered to your game ID.',
  'order.note.completedCode': 'Your code is ready in the Vault.',
  'order.note.failed': "We couldn't deliver this order. {amount} was returned to your balance.",
  'order.note.refunded': '{amount} was returned to your balance.',
  'status.pending': 'Pending',
  'status.processing': 'Processing',
  'status.completed': 'Completed',
  'status.failed': 'Failed',
  'status.refunded': 'Refunded',

  // vault
  'vault.title': 'Vault',
  'vault.subtitle': 'Codes for gift cards, game keys and subscriptions.',
  'vault.emptyTitle': 'No codes yet',
  'vault.emptyBody':
    'Gift card, game key and subscription codes you buy show up here. Diamonds and UC go straight to your game ID.',
  'vault.reveal': 'Reveal',
  'vault.hide': 'Hide',
  'vault.used': 'Used',
  'vault.markUsed': 'Mark as used',
  'vault.unused': 'Ready to use',
  'vault.paidAmount': 'Paid {amount}',

  // profile
  'profile.title': 'Profile',
  'profile.history': 'Transactions',
  'profile.noHistory': 'No transactions yet.',
  'profile.language': 'Language',
  'profile.support': 'Support',
  'profile.supportBody': 'Need help with an order or a top-up?',
  'profile.signOut': 'Sign out',
  'profile.adminView': 'Switch to admin view',
  'notif.title': 'Notifications',
  'notif.empty': 'No notifications yet',
  'notif.emptyHint': 'Discounts and wallet updates will show up here.',
  'notif.unreadRow': 'Unread',
  'gift.menu.title': 'Gift',
  'gift.menu.body': 'Buy a pack for someone else. It waits in their Vault until they claim it.',
  'gift.send.title': 'Send to a friend',
  'gift.send.body': 'Find them by email. It goes straight to their Vault.',
  'gift.code.title': 'Create a redeem code',
  'gift.code.body': 'Get a code you can hand to anyone.',
  'gift.email.label': "Your friend's Gmail",
  'gift.email.placeholder': 'name@gmail.com',
  'gift.email.find': 'Find',
  'gift.email.invalid': 'Enter their full email address.',
  'gift.email.notFound': 'No Portal account uses this email. Check it and try again.',
  'gift.email.self': "That's your own account. You can't send a gift to yourself.",
  'gift.email.tooMany': 'Too many searches. Wait a few minutes and try again.',
  'gift.email.error': "Couldn't search right now. Try again.",
  'gift.confirm.title': 'Your gift goes to',
  'gift.confirm.choose': 'Choose a pack for {name}',
  'gift.confirm.change': 'Not them? Change the email',
  'gift.banner.gift': 'Gift for {name}',
  'gift.banner.code': 'Buying a redeem code',
  'gift.banner.hint': "No player ID now: it's asked when the gift is claimed.",
  'gift.banner.cancel': 'Cancel gift',
  'gift.buy.gift': 'Gift this pack',
  'gift.buy.code': 'Buy redeem code',
  'gift.error.pack': 'This pack is no longer available. Pick another one.',
  'gift.error.pending': 'You have an unpaid order. Finish or cancel it first.',
  'gift.error.other': "Couldn't buy the gift. Try again.",
  'gift.done.giftTitle': 'Gift sent',
  'gift.done.giftBody': "{pack} is waiting in {name}'s Vault. They'll claim it there.",
  'gift.done.codeTitle': 'Your redeem code',
  'gift.done.codeBody': 'For {pack}. Copy it now and send it to anyone.',
  'gift.done.codeUse': 'Anyone with this code can redeem it in Profile → Redeem code. You will also find it in your Vault.',
  'gift.done.codeSecret': 'Treat it like cash: whoever sees it can use it.',
  'gift.done.copy': 'Copy code',
  'gift.done.expires': 'Unused codes and gifts expire after 90 days.',
  'gift.done.done': 'Done',
  'gift.done.waiting': 'Waiting for your payment to be confirmed…',
  'vault.filter.all': 'All',
  'vault.filter.cards': 'Gift cards',
  'vault.filter.gifts': 'Gifts',
  'vault.filter.codes': 'Redeem codes',
  'vault.emptyGifts': 'No gifts yet. When someone sends you one, it waits here for you to claim.',
  'vault.emptyCodes': 'No redeem codes yet. Buy one in Profile → Gift.',
  'vault.gift.badge': 'Gift',
  'vault.gift.from': 'From {name}',
  'vault.gift.fromCode': 'From a redeem code',
  'vault.gift.claimWithin': 'Claim within {n} days',
  'vault.gift.claimToday': 'Claim today, it expires soon',
  'vault.gift.claim': 'Claim gift',
  'vault.gift.claimed': 'Claimed',
  'vault.gift.expired': 'Expired',
  'vault.gift.delivering': 'Claimed, being delivered',
  'vault.gift.delivered': 'Claimed and delivered',
  'vault.gift.view': 'View delivery',
  'vault.gift.deliveredToast': 'Gift claimed and delivered',
  'vault.gift.queued': "Claimed! Delivery didn't finish right away. It's queued and our team will complete it for you.",
  'vault.gift.regionWrong': "This pack isn't for your account's region ({region}).",
  'vault.claimErr.gift_already_claimed': 'This gift was already claimed.',
  'vault.claimErr.gift_expired': 'This gift has expired.',
  'vault.claimErr.gift_not_yours': 'This gift was sent to another account.',
  'vault.claimErr.gift_not_found': 'This gift no longer exists.',
  'vault.claimErr.pack_unavailable': "This pack isn't available right now. Try again later.",
  'vault.claimErr.player_id_required': 'Enter your player ID first.',
  'vault.claimErr.id_fields_invalid': "That ID doesn't look right. Check it and try again.",
  'vault.claimErr.id_not_validated': 'Wait for your ID to be checked, then claim.',
  'vault.claimErr.id_validation_expired': 'Your ID check ran out. Check it again, then claim.',
  'vault.claimErr.region_unverifiable': "Your account's region can't be checked for this pack.",
  'vault.claimErr.region_unverified': "Your account's region couldn't be confirmed, so this pack can't be sent to it.",
  'vault.claimErr.region_mismatch': "This pack isn't for your account's region.",
  'vault.claimErr.not_authenticated': 'Sign in again to claim.',
  'vault.claimErr.unknown': "Couldn't claim it right now. Check your connection and try again.",
  'vault.code.active': 'Not used yet',
  'vault.code.redeemed': 'Redeemed',
  'vault.code.expired': 'Expired',
  'vault.code.hint': 'Anyone can redeem it in Profile → Redeem code.',
  'notif.giftReceived.title': 'You received a gift',
  'notif.giftReceived.body': '{name} sent you {product} {pack}. Claim it in your Vault.',
  'notif.giftClaimed.title': 'Your gift was claimed',
  'notif.giftClaimed.body': '{name} claimed the {product} {pack} you sent.',
  'notif.codeRedeemed.title': 'Your redeem code was used',
  'notif.codeRedeemed.body': 'Your {product} {pack} code was redeemed.',
  'notif.giftDelivered.title': 'Your gift has arrived',
  'notif.giftDelivered.body': '{product} {pack} is delivered.',
  'notif.opens.vault': 'Opens your Vault',
  'notif.opens.receipt': 'Opens your receipt',
  'notif.tournamentTeam.title': 'New team registered',
  'notif.tournamentTeam.body': '{team} registered for {tournament} ({n} of {total} teams).',
  'notif.tournamentJoined.title': "You're in a tournament team",
  'notif.tournamentJoined.body': '{name} added you to team {team} for {tournament}.',
  'notif.tournamentStarting.title': 'Tournament starting soon',
  'notif.tournamentStarting.body': '{tournament} starts in a few minutes. Get ready!',
  'notif.tournamentCancelled.title': 'Tournament cancelled',
  'notif.tournamentCancelled.body': '{tournament} was cancelled. Any entry fee you paid is back in your wallet.',
  'notif.opens.tournament': 'Opens the tournament',
  'notif.tournamentRefunded.title': "Registration didn't go through",
  'notif.tournamentRefunded.body': '{tournament}: the payment is back in your wallet.',
  'tx.tournament': 'Tournament',
  'order.gift.title': 'Gift received',
  'order.gift.from': 'A gift to you',
  'order.gift.deliveredTo': 'Delivered to',
  'order.gift.noReceipt': 'Nothing was charged to you. The receipt stays with the person who bought it.',
  'order.gift.buyerGift': 'Gift sent. It waits in their Vault until they claim it.',
  'order.gift.buyerCode': 'Your redeem code is in your Vault. Share it with whoever should get it.',
  'gift.done.receipt': 'View receipt',
  'gift.choice.title': 'Choose the server',
  'gift.choice.hintGift': 'Pick it for them. They\'ll only type their player ID when they claim it.',
  'gift.choice.hintCode': 'Pick it now. Whoever redeems the code only types their player ID.',
  'gift.error.choice': 'Choose the server first.',
  'vault.gift.chosen': '{label}: {value}',
  'redeem.title': 'Redeem code',
  'redeem.body': 'Got a code from someone? Enter it to add the gift to your Vault.',
  'redeem.label': 'Code',
  'redeem.placeholder': 'ABCDE FGHIJ',
  'redeem.paste': 'Paste',
  'redeem.submit': 'Redeem',
  'redeem.short': 'A code has 10 letters and numbers.',
  'redeem.err.invalid': 'That code doesn\'t work. Check each character and try again.',
  'redeem.err.mine': 'You\'ve already redeemed this code. It\'s in your Vault.',
  'redeem.err.tooMany': 'Too many tries. Wait 10 minutes, then try again.',
  'redeem.err.error': 'Couldn\'t check the code right now. Check your connection and try again.',
  'redeem.done.title': 'Added to your Vault',
  'redeem.done.body': 'Claim it now, or later from your Vault.',
  'redeem.openVault': 'Open Vault',
  'redeem.another': 'Redeem another code',
  'gift.terms.title': 'Before you buy',
  'gift.terms.noRefund': 'Gifts and redeem codes can\'t be refunded. Unused ones expire after 90 days.',
  'gift.terms.regionGift': 'This pack only works for game accounts in {regions}. Make sure theirs is in that region: an account elsewhere can\'t claim it.',
  'gift.terms.regionCode': 'This pack only works for game accounts in {regions}. Whoever redeems the code needs an account in that region.',
  'gift.confirm.titleGift': 'Buy this gift?',
  'gift.confirm.titleCode': 'Buy this redeem code?',
  'gift.confirm.bodyGift': '{pack} for {name}, {price}. Gifts can\'t be refunded.',
  'gift.confirm.bodyCode': '{pack} as a redeem code, {price}. Redeem codes can\'t be refunded.',
  'gift.confirm.buy': 'Buy',
  'orders.gift.sent': 'Gift sent',
  'orders.gift.code': 'Redeem code',
  'orders.gift.received': 'Gift received',
  'orders.gift.state.pending': 'waiting to be claimed',
  'orders.gift.state.claimed': 'claimed',
  'orders.gift.state.expired': 'expired',
  'orders.gift.state.active': 'not redeemed yet',
  'orders.gift.state.redeemed': 'redeemed',
  'pay.viewGift': 'See your gift',
  'notif.bellUnread': 'Notifications, {n} unread',
  'notif.now': 'now',
  'notif.minutes': '{n}m',
  'notif.hours': '{n}h',
  'notif.days': '{n}d',
  'notif.discount.title': 'Now discounted',
  'notif.discount.body': '{product} {pack} now {percent}% off',
  'notif.deposit.title': 'Deposit approved',
  'notif.deposit.body': '{amount} added to your wallet',
  'notif.refund.title': 'Refund credited',
  'notif.refund.body': '{amount} refunded to your wallet',
  'notif.commission.title': 'Commission earned',
  'notif.commission.body': '{amount} from code {code}',
  'notif.commissionNoCode.body': '{amount} commission added to your wallet',
  'notif.withdrawal.title': 'Withdrawal sent',
  'notif.withdrawal.body': '{amount} sent to you',
  'notif.opens.discountPack': 'Opens {product}, discounted pack',
  'notif.opens.product': 'Opens {product}',
  'notif.opens.deposit': 'Opens your deposit in Transactions',
  'notif.opens.refund': 'Opens your refund in Transactions',
  'notif.opens.commission': 'Opens your commission in Transactions',
  'notif.opens.withdrawal': 'Opens your withdrawal in Transactions',
  'accounts.add': 'Add account',
  'accounts.active': 'Active',
  'accounts.removeHint': 'Long-press to remove it from this device',
  'accounts.limitHint': '3 of 3 · long-press an account to remove it',
  'accounts.limitBody': 'You can keep up to 3 accounts on this device. Long-press one to remove it, then add the new one.',
  'accounts.removeTitle': 'Remove from this device?',
  'accounts.removeBody': "This only removes {name} from this device. The account isn't deleted or signed out anywhere else.",
  'accounts.removeActiveBody': "You're using {name} now. Removing it signs it out on this device only; it isn't deleted or signed out anywhere else.",
  'accounts.remove': 'Remove',
  'accounts.expiredTitle': 'Sign in again',
  'accounts.expiredBody': '{name} is no longer signed in on this device. Sign in again to keep using it here.',
  'accounts.signInAgain': 'Sign in again',
  'accounts.needsSignIn': 'Signed out · tap to sign in',
  'accounts.switchFailed': "Couldn't switch accounts. Try again.",
  'settings.title': 'Settings',
  'settings.editProfile': 'Edit profile',
  'settings.account': 'Account',
  'settings.privacy': 'Privacy',
  'editProfile.changePhoto': 'Change photo',
  'editProfile.name': 'Display name',
  'editProfile.save': 'Save',
  'editProfile.saved': 'Profile saved',
  'editProfile.nameInvalid': 'Use 2 to 40 characters.',
  'editProfile.photoSaved': 'Photo updated',
  'editProfile.photoFailed': "Couldn't update your photo. Try again.",
  'account.google': 'Google',
  'account.emailPassword': 'Email and password',
  'account.changePassword': 'Change password',
  'account.currentPassword': 'Current password',
  'account.newPassword': 'New password',
  'account.wrongPassword': 'Your current password is wrong.',
  'account.samePassword': 'Choose a password different from your current one.',
  'account.passwordChanged': 'Password changed',
  'account.passwordFailed': "Couldn't change your password. Try again.",
  'account.sectionSignIn': 'Sign-in',
  'account.sectionSecurity': 'Security',
  'account.connected': 'Connected',
  'account.passwordSet': 'Set',
  'account.passwordNotSet': 'Not set',
  'account.addPassword': 'Add a password',
  'account.addPasswordBody': 'Add a password so you can also sign in with your email, not only with Google.',
  'account.confirmPassword': 'Confirm new password',
  'account.mismatch': "The two passwords don't match.",
  'account.passwordAdded': 'Password added',
  'account.network': 'No connection. Check your internet, then try again.',
  'privacy.policy': 'Privacy policy',
  'privacy.deleteAccount': 'Request account deletion',
  'privacy.deleteBody': 'To have your account and its data deleted, contact support and ask. We handle every request by hand.',
  'tx.deposit': 'Deposit',
  'tx.purchase': 'Purchase',
  'tx.refund': 'Refund',
  'tx.adjustment': 'Adjustment',

  // top up
  'topup.title': 'Top up',
  'topup.body':
    'Send your payment, then message us. We add the money to your balance as soon as we confirm it.',
  'topup.noContact': 'Ask the shop to add balance to your account.',
  'topup.account': 'Your account',
  'topup.contact': 'Contact support',
  ...CART_STRINGS,
  ...WALLET_STRINGS,
  ...AUTH_STRINGS_EN,
  ...UI_STRINGS_EN,
  ...WHEEL_STRINGS_EN,
  ...HEADER_STRINGS_EN,
  ...TOURNAMENT_STRINGS_EN,
} as const;

export type StringKey = keyof typeof en;

/**
 * Amharic for the cart, payment, wallet, deposit and withdraw screens: short labels, statuses, buttons and plain messages.
 * Money-critical instruction sentences are NOT here: they stay English (see AM_NEEDS_REVIEW) until a native speaker approves
 * them, because a wrong word in "how to pay" or "what a mismatch means" costs someone money. Drafts: AMHARIC_REVIEW.md.
 */
const AM_CART_WALLET = {
  'cart.title': 'ጋሪ',
  'cart.empty': 'ጋሪዎ ባዶ ነው',
  'cart.emptyBody': 'ከጨዋታ ገጽ ጥቅሎችን ወደ ጋሪ ያክሉ፣ ከዚያ እዚህ ክፍያ ይፈጽሙ።',
  'cart.browse': 'ጨዋታዎችን ይመልከቱ',
  'cart.add': 'ወደ ጋሪ ጨምር',
  'cart.added': 'ወደ ጋሪ ተጨምሯል',
  'cart.remove': 'አስወግድ',
  'cart.qty': 'ብዛት',
  'cart.total': 'ጠቅላላ',
  'cart.checkout': 'ክፍያ ፈጽም',
  'cart.unavailable': 'ከዚህ በኋላ አይገኝም',
  'cart.unavailableBody': 'ለመቀጠል ያስወግዱት።',
  'cart.fixFirst': 'መጀመሪያ እነዚህን ያስተካክሉ፦',
  'cart.problem.fill_fields': 'መለያውን ያስገቡ',
  'cart.problem.checking': 'መለያውን በመፈተሽ ላይ…',
  'cart.problem.invalid_id': 'መለያው ትክክል አይደለም',
  'cart.problem.check_failed': 'መለያውን መፈተሽ አልተቻለም፣ እንደገና ይሞክሩ',
  'cart.problem.check_expired': 'የፍተሻው ጊዜ አልፏል፣ እንደገና ይፈትሹ',
  'cart.problem.confirm_id': 'መለያዎን እንደፈተሹ ምልክት ያድርጉ',
  'cart.problem.wrong_region': 'ይህ ጥቅል ለዚያ መለያ ክልል አይደለም',
  'cart.problem.region_unknown': 'የመለያው ክልል ሊረጋገጥ አልቻለም',
  'cart.problem.unavailable': 'ከዚህ በኋላ አይገኝም',
  'cart.problem.package_unavailable': 'አይገኝም',
  'cart.problem.choose_package': 'አይገኝም',
  'cart.dropped': 'እነዚህ እቃዎች ከዚህ በኋላ አይሸጡም፤ ተወግደዋል፦ {items}',
  'cart.fixIds': 'የእነዚህ እቃዎች የተጫዋች መለያ እንደገና መፈተሽ አለበት፦ {items}',
  'cart.checkoutFailed': 'ክፍያውን መጀመር አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'cart.loadError': 'ጋሪዎን መጫን አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'cart.pending': 'ክፍያ የሚጠብቅ ትዕዛዝ አለዎት።',
  'cart.codeLabel': 'የቅናሽ ኮድ (አማራጭ)',
  'cart.codePlaceholder': 'ኮድ ያስገቡ',
  'cart.codeApply': 'ተግብር',
  'cart.codeApplyPercent': 'ተግብር -{percent}%',
  'cart.codeApplied': 'ኮድ ተተግብሯል፦ -{amount}',
  'cart.codeChecking': 'ኮዱን በመፈተሽ ላይ…',
  'cart.code.notFound': 'ይህ ኮድ የለም። ኮዱን አረጋግጠው እንደገና ይሞክሩ።',
  'cart.code.inactive': 'ይህ ኮድ ከዚህ በኋላ ንቁ አይደለም።',
  'cart.code.expired': 'የዚህ ኮድ ጊዜ አልፏል።',
  'cart.code.notApplicable': 'ይህ ኮድ በጋሪዎ ውስጥ ላለ ምንም ነገር አይሠራም።',
  'cart.code.alreadyUsed': 'ይህን ኮድ አስቀድመው ተጠቅመውበታል።',
  'cart.code.alreadyUsedBonus': 'አስቀድመው ተጠቅመውበታል — ከቅናሽ ይልቅ +{n} ፖርታል ኮይኖች ያገኛሉ።',
  'cart.wheelUnavailable': 'ያ ሽልማት ከዚህ በኋላ አይገኝም።',
  'cart.payWallet': 'ወዲያውኑ ከቦርሳዎ ይከፈላል (ቀሪ ሂሳብ {balance})።',
  'cart.payBank': 'ቦርሳዎ ({balance}) ይህን አይሸፍንም፤ ስለዚህ በቀጣይ በቴሌብር ወይም በCBE ይከፍላሉ።',
  'cart.checkoutWallet': 'ከቦርሳ {amount} ክፈል',
  'pay.title': 'ክፍያ',
  'pay.amount': 'በትክክል ይላኩ',
  'pay.method': 'የመክፈያ መንገድ',
  'pay.telebirr': 'ቴሌብር',
  'pay.cbe': 'CBE',
  'pay.sendTo': 'የሚላክበት',
  'pay.accountName': 'የመለያ ስም',
  'pay.accountNumber': 'የመለያ ቁጥር',
  'pay.ref.telebirr': 'የቴሌብር የግብይት ቁጥር',
  'pay.ref.cbe': 'የCBE የግብይት መለያ',
  'pay.refHint.telebirr': 'በቴሌብር ደረሰኝዎ ወይም በአጭር መልዕክትዎ (SMS) ውስጥ ያገኙታል።',
  'pay.refHint.cbe': 'በCBE ደረሰኝዎ ወይም በአጭር መልዕክትዎ ላይ ያገኙታል። በFT ይጀምራል።',
  'pay.refRequired': 'ከክፍያ ደረሰኝዎ የግብይት ቁጥሩን ያስገቡ።',
  'pay.submit': 'ክፍያውን አረጋግጥ',
  'pay.verifying': 'ክፍያዎን በማረጋገጥ ላይ…',
  'pay.wait': 'አሁንም በማረጋገጥ ላይ ነው። ትንሽ ሊወስድ ይችላል።',
  'pay.paidTitle': 'ክፍያው ተሳክቷል!',
  'pay.paidBody': 'ምርትዎን በቅርቡ ይደርስዎታል።',
  'pay.viewReceipt': 'ደረሰኙን ይመልከቱ',
  'pay.moreItems': '+{n} ተጨማሪ',
  'pay.mismatchTitle': 'ክፍያዎን እየገመገምን ነው',
  'pay.closed': 'ይህ ትዕዛዝ ከዚህ በኋላ ክፍያ አይጠብቅም።',
  'pay.cancel': 'ትዕዛዙን ሰርዝ',
  'pay.cancelTitle': 'ትዕዛዙ ይሰረዝ?',
  'pay.cancelled': 'ትዕዛዙ ተሰርዟል። እቃዎችዎ ወደ ጋሪዎ ተመልሰዋል።',
  'pay.items': 'በዚህ ትዕዛዝ ውስጥ',
  'pay.viewOrders': 'ትዕዛዞቼን ተመልከት',
  'pay.viewVault': 'ወደ ካዝናዬ ይሂዱ',
  'pay.loadError': 'ይህን ትዕዛዝ መጫን አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'pay.wallet': 'ከቦርሳ {amount} ክፈል',
  'pay.walletOr': 'ቦርሳዎ ይህን ትዕዛዝ ይሸፍናል',
  'pay.walletFailed': 'ከቦርሳ መክፈል አልተቻለም። ቀሪ ሂሳብዎ ተቀይሮ ሊሆን ይችላል። ምንም አልተወሰደም።',
  'pay.discountApplied': 'ኮድ ተተግብሯል፦ -{amount}',
  'status.pending_payment': 'ክፍያ በመጠበቅ ላይ',
  'status.paid': 'ተከፍሏል',
  'status.payment_mismatch': 'በመገምገም ላይ',
  'status.cancelled': 'ተሰርዟል',
  'order.note.pending_payment': 'ክፍያዎን እየጠበቅን ነው። ለመጨረስ ይክፈቱት።',
  'order.note.paid': 'ክፍያ ተረጋግጧል።',
  'order.note.cancelled': 'ይህ ትዕዛዝ ተሰርዟል።',
  'order.items': 'እቃዎች',
  'tx.withdrawal': 'ወጪ',
  'tx.commission': 'ኮሚሽን',
  'tx.portal_coin_redemption': 'ፖርታል ኮይኖች ተቀይረዋል',
  'product.buyNow': 'አሁን ግዛ',
  'wallet.title': 'ቦርሳ',
  'wallet.balance': 'ቀሪ ሂሳብ',
  'wallet.deposit': 'ገንዘብ አስገባ',
  'wallet.withdraw': 'ገንዘብ አውጣ',
  'wallet.history': 'ታሪክ',
  'wallet.noHistory': 'ገና ምንም ግብይት የለም።',
  'wallet.after': 'ቀሪ ሂሳብ {balance}',
  'wallet.openDeposit': 'የ{amount} ገቢ ክፍያዎን እየጠበቀ ነው',
  'wallet.openDepositBody': 'ገንዘቡን ይላኩ፣ ከዚያ ወደ ቀሪ ሂሳብዎ ለመጨመር የግብይት ቁጥሩን ያስገቡ።',
  'wallet.continue': 'ቀጥል',
  'wallet.withdrawals': 'የገንዘብ ማውጫ ጥያቄዎችዎ',
  'wallet.wd.pending': 'በመጠበቅ ላይ',
  'wallet.wd.approved': 'ጸድቋል',
  'wallet.wd.paid': 'ተከፍሏል',
  'wallet.wd.declined': 'ውድቅ ተደርጓል',
  'wallet.declinedNote': 'ወደ ቀሪ ሂሳብዎ ተመልሷል። ምክንያት፦ {note}',
  'portalCoin.balance': '{n} ፖርታል ኮይኖች',
  'portalCoin.earned': '+{n} ፖርታል ኮይኖች ተገኝተዋል',
  'wallet.err.invalid_amount': 'ይህ መጠን አይፈቀድም።',
  'wallet.err.invalid_provider': 'ቴሌብር ወይም CBE ይምረጡ።',
  'wallet.err.invalid_account': 'የመለያ ቁጥሩ ትክክል አይመስልም። ያረጋግጡና እንደገና ይሞክሩ።',
  'wallet.err.insufficient_balance': 'ለዚህ በቂ ቀሪ ሂሳብ የለዎትም።',
  'wallet.err.deposit_open': 'ክፍያ የሚጠብቅ ገቢ አስቀድሞ አለዎት።',
  'wallet.err.too_many_pending': 'ብዙ የገንዘብ ማውጫ ጥያቄዎች በመጠበቅ ላይ ናቸው። መጀመሪያ አንዳንዶቹ እስኪስተናገዱ ይጠብቁ።',
  'wallet.err.unauthorized': 'እባክዎ እንደገና ይግቡ።',
  'wallet.err.unavailable': 'አገልጋዩን ማግኘት አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'deposit.title': 'ገንዘብ አስገባ',
  'deposit.lead': 'ወደ ቀሪ ሂሳብዎ በቴሌብር ወይም በCBE ገንዘብ ይጨምሩ። ክፍያዎ እንደተረጋገጠ እንጨምራለን።',
  'deposit.amount': 'መጠን (ብር)',
  'deposit.quick': 'ፈጣን መጠኖች',
  'deposit.start': 'ቀጥል',
  'deposit.problem.required': 'መጠን ያስገቡ።',
  'deposit.problem.min': 'ትንሹ ገቢ {min} ነው።',
  'deposit.problem.max': 'ትልቁ ገቢ {max} ነው።',
  'deposit.sendExactly': 'በትክክል ይላኩ',
  'deposit.cancel': 'መጠኑን ቀይር',
  'deposit.cancelTitle': 'መጠኑ ይቀየር?',
  'deposit.cancelFailed': 'መሰረዝ አልተቻለም። እንደገና ይሞክሩ።',
  'deposit.paidTitle': 'ገቢ ተቀብለናል',
  'deposit.paidBody': '{amount} ወደ ቀሪ ሂሳብዎ ተጨምሯል።',
  'deposit.mismatchTitle': 'መጠኑ አይመሳሰልም',
  'deposit.done': 'ተጠናቋል',
  'withdraw.title': 'ገንዘብ አውጣ',
  'withdraw.amount': 'መጠን (ብር)',
  'withdraw.to': 'ገንዘቤ የሚላክበት',
  'withdraw.account.telebirr': 'የቴሌብር ቁጥርዎ',
  'withdraw.account.cbe': 'የCBE መለያ ቁጥርዎ',
  'withdraw.account.required': 'የሚላክበትን መለያ ያስገቡ።',
  'withdraw.account.invalid': 'ቁጥሩ ትክክል አይመስልም።',
  'withdraw.accountHint.telebirr': 'በቴሌብር የተመዘገበው ስልክ ቁጥር፣ ለምሳሌ 0911 22 33 44።',
  'withdraw.accountHint.cbe': 'የ13 አሃዝ የCBE መለያ ቁጥርዎ።',
  'withdraw.problem.required': 'መጠን ያስገቡ።',
  'withdraw.problem.min': 'ትንሹ የማውጫ መጠን {min} ነው።',
  'withdraw.problem.balance': 'ይህ ከቀሪ ሂሳብዎ ({balance}) ይበልጣል።',
  'withdraw.submit': 'ማውጫ ጠይቅ',
  'withdraw.confirmTitle': 'ወደዚህ መለያ ይላክ?',
  'withdraw.confirm': 'ጠይቅ',
  'withdraw.doneTitle': 'ጥያቄው ተልኳል',
} as const;

/** Amharic strings that are still ENGLISH on purpose, waiting for a native speaker. A test keeps this list honest. */
export const AM_NEEDS_REVIEW = [
  'pay.noAccount',
  'pay.steps.telebirr',
  'pay.steps.cbe',
  'pay.mismatchBody',
  'pay.notVerified.not_found',
  'pay.notVerified.provider_mismatch',
  'pay.notVerified.pending',
  'pay.notVerified.invalid_request',
  'pay.notVerified.unknown',
  'pay.referenceUsed',
  'pay.tryLater',
  'pay.cancelBody',
  'pay.cancelFailed',
  'order.note.payment_mismatch',
  'deposit.exactNote',
  'deposit.cancelBody',
  'deposit.mismatchBody',
  'withdraw.note',
  'withdraw.confirmBody',
  'withdraw.doneBody',
  'redeem.err.invalid',
  'redeem.err.mine',
  'redeem.err.tooMany',
  'redeem.err.error',
  'redeem.done.body',
  'gift.terms.noRefund',
  'gift.terms.regionGift',
  'gift.terms.regionCode',
  'gift.confirm.bodyGift',
  'gift.confirm.bodyCode',
  'order.gift.noReceipt',
  ...TOURNAMENT_AM_NEEDS_REVIEW,
  'notif.tournamentCancelled.body',
  'notif.tournamentRefunded.body',
] as const satisfies readonly StringKey[];

export const am: Record<StringKey, string> = {
  'tab.shop': 'ሱቅ',
  'tab.orders': 'ትዕዛዞች',
  'tab.vault': 'ካዝና',
  'tab.profile': 'መገለጫ',

  'a11y.openOrders': '{n} ክፍት ትዕዛዞች',
  'a11y.newCodes': '{n} አዲስ ኮዶች',

  'common.balance': 'ቀሪ ሂሳብ',
  'common.retry': 'እንደገና ሞክር',
  'common.cancel': 'ሰርዝ',
  'common.copy': 'ቅዳ',
  'common.copied': 'ተቀድቷል',
  'common.loadError': 'መጫን አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'common.topUp': 'ሂሳብ ሙላ',

  'time.now': 'አሁን',
  'time.min': 'ከ{n} ደቂቃ በፊት',
  'time.hour': 'ከ{n} ሰዓት በፊት',
  'time.day': 'ከ{n} ቀን በፊት',

  'shop.search': 'ጨዋታ፣ የስጦታ ካርድ፣ ቁልፍ ፈልግ',
  'shop.buyAgain': 'እንደገና ግዛ',
  'shop.loading': 'ምርቶች በመጫን ላይ',
  'shop.seeAll': 'ሁሉንም እይ',
  'shop.seeAllIn': 'ሁሉንም {name} እይ',
  'shop.results': 'ውጤቶች',
  'shop.noResults': 'ለ“{q}” ምንም ውጤት የለም',
  'shop.noResultsBody': 'ፊደሉን ያረጋግጡ ወይም ሌላ ጨዋታ ወይም የስጦታ ካርድ ይፈልጉ።',
  'shop.clear': 'ፍለጋውን አጽዳ',
  'shop.emptyTitle': 'እዚህ ገና ምንም የለም',
  'shop.emptyBody': 'አዳዲስ ምርቶች እንደተዘጋጁ እዚህ ይታያሉ።',
  'shop.errorTitle': 'ምርቶችን መጫን አልተቻለም',
  'shop.addBalance': 'ሂሳብ መሙላት ገና አይገኝም።',
  'cat.gift-cards': 'የስጦታ ካርዶች',
  'cat.game-keys': 'የጨዋታ ቁልፎች',
  'cat.games': 'ጨዋታዎች',
  'cat.subscriptions': 'ምዝገባዎች',

  'product.choose': 'መጠን ይምረጡ',
  'product.gameId': 'የጨዋታ መለያ (ID)',
  'product.gameIdHint': 'በጨዋታው ውስጥ እንደሚታየው የተጫዋች መለያዎን በትክክል ያስገቡ።',
  'product.paste': 'ለጥፍ',
  'product.pay': '{price} ክፈል',
  'product.yourBalance': 'ቀሪ ሂሳብዎ',
  'product.notEnough': 'በቂ ቀሪ ሂሳብ የለም',
  'product.placed': 'ትዕዛዝዎ ተልኳል',
  'product.placedTopup': 'በቅርቡ ወደ ጨዋታ መለያዎ እንልካለን።',
  'product.placedCode': 'ኮዱ እንደተዘጋጀ በካዝናዎ ውስጥ ይታያል።',
  'product.viewOrder': 'ትዕዛዙን እይ',
  'product.backToShop': 'ወደ ሱቅ ተመለስ',
  'product.notFound': 'ይህ ምርት ከእንግዲህ አይገኝም።',
  'product.codeNote': 'ኮድ ያገኛሉ። ወደ ካዝናዎ ይደርሳል።',
  'product.topupNote': 'በቀጥታ ወደ ጨዋታ መለያዎ ይላካል።',
  'product.region': 'ክልል',
  'product.idTitle': 'የተጫዋች መለያዎ',
  'product.checking': 'በመፈተሽ ላይ…',
  'product.playerRegion': 'የመለያ ክልል፦ {region}',
  'product.playerLabel': 'ተጫዋች፦ {name}',
  'product.retry': 'እንደገና ሞክር',
  'product.checkAgain': 'እንደገና ፈትሽ',
  'product.check.invalid': 'ያንን የተጫዋች መለያ ማግኘት አልተቻለም። ያረጋግጡና እንደገና ይሞክሩ።',
  'product.check.failed': 'መለያውን አሁን መፈተሽ አልተቻለም።',
  'product.check.timeout': 'ፍተሻው ከመጠን በላይ እየወሰደ ነው።',
  'product.check.expired': 'ይህ ፍተሻ ጊዜው አልፎበታል። መለያውን እንደገና ይፈትሹ።',
  'product.regionAuto': 'ከመለያዎ ጋር እንዲመሳሰል {region} ተመርጧል።',
  'product.regionWrong': 'መለያዎ በ{account} ክልል ውስጥ ነው። በ{region} ያሉ ጥቅሎች ለእሱ አይሰሩም።',
  'product.regionSwitch': 'ወደ {region} ቀይር',
  'product.regionNone': 'ይህንን በ{account} ክልል ላሉ መለያዎች አንሸጥም።',
  'product.regionUnknown': 'የመለያዎን ክልል ማረጋገጥ ስላልቻልን ለክልል የተወሰኑ ጥቅሎችን መሸጥ አንችልም።',
  'product.packWrongRegion': 'ለመለያዎ ክልል አይደለም',
  'product.packUnknownRegion': 'ክልሉ አልተረጋገጠም',
  'product.packUnavailable': 'አይገኝም',
  'product.tick': 'የመለያዬ ትክክለኛነት አረጋግጫለሁ። ግዢዎች መመለስ አይችሉም።',
  'product.total': 'ጠቅላላ',
  'product.continue': 'ቀጥል',
  'product.was': 'ቀድሞ {price}',
  'product.off': '{pct}% ቅናሽ',
  'product.blocker.choose': 'ጥቅል ይምረጡ',
  'product.blocker.fill': 'መለያዎን ያስገቡ',
  'product.blocker.checking': 'መለያዎ በመፈተሽ ላይ…',
  'product.blocker.invalid': 'ለመቀጠል መለያዎን ያስተካክሉ',
  'product.blocker.failed': 'ለመቀጠል ፍተሻውን እንደገና ይሞክሩ',
  'product.blocker.expired': 'ለመቀጠል መለያዎን እንደገና ይፈትሹ',
  'product.blocker.confirm': 'ለመቀጠል ሳጥኑን ምልክት ያድርጉ',
  'product.blocker.wrongRegion': 'ለመለያዎ ክልል የሚሆን ጥቅል ይምረጡ',
  'product.blocker.regionUnknown': 'ይህ ጥቅል ለመለያዎ ሊሸጥ አይችልም',
  'product.blocker.unavailable': 'ይህ ጥቅል አይገኝም',
  'product.confirmTitle': 'ትዕዛዝዎን ያረጋግጡ',
  'product.item': 'ጥቅል',
  'product.player': 'ተጫዋች',
  'product.price': 'ዋጋ',
  'product.balanceAfter': 'ከክፍያ በኋላ ቀሪ ሂሳብ',
  'product.confirmPay': 'አረጋግጥና {price} ክፈል',
  'product.cancel': 'ተው',
  'product.verifying': 'የቅርብ ጊዜውን ዋጋ በመፈተሽ ላይ…',

  'err.insufficient': 'በቂ ቀሪ ሂሳብ የለም። ሂሳብ ሞልተው እንደገና ይሞክሩ።',
  'err.unavailable': 'ይህ ምርት ከእንግዲህ አይገኝም።',
  'err.accountId': 'ትክክለኛ የጨዋታ መለያ ያስገቡ።',
  'err.generic': 'የሆነ ችግር ተፈጥሯል። እባክዎ እንደገና ይሞክሩ።',
  'err.packageGone': 'ያ ጥቅል ከእንግዲህ አይገኝም።',
  'err.priceChanged': 'ዋጋው ከ{old} ወደ {now} ተቀይሯል። ይመልከቱና ዝግጁ ሲሆኑ ይቀጥሉ።',
  'err.idNotValidated': 'መለያዎን እንደገና መፈተሽ አለብን።',
  'err.idExpired': 'የመለያ ፍተሻዎ ጊዜው አልፏል። እንደገና ይፈትሹ።',
  'err.idCheckRequired': 'መለያዎን ለማረጋገጥ ሳጥኑን ምልክት ያድርጉ።',
  'err.regionMismatch': 'ይህ ጥቅል ለመለያዎ ክልል ({region}) አይገኝም።',
  'err.regionUnverified': 'የመለያዎን ክልል ማረጋገጥ ስላልቻልን ይህ ጥቅል መገዛት አይችልም።',

  'orders.title': 'ትዕዛዞች',
  'orders.emptyTitle': 'ገና ምንም ትዕዛዝ የለም',
  'orders.emptyBody': 'ግዢዎችዎ እዚህ ይታያሉ።',
  'orders.detail': 'የትዕዛዝ ዝርዝር',
  'order.item': 'ምርት',
  'order.amount': 'መጠን',
  'order.placed': 'የታዘዘበት ጊዜ',
  'order.gameId': 'የጨዋታ መለያ',
  'order.region': 'ክልል',
  'order.verified': 'መለያው ከማዘዙ በፊት ከጨዋታው ጋር ተፈትሿል',
  'order.verifiedPlayer': 'ተጫዋች፦ {name}',
  'order.verifiedRegion': 'የመለያ ክልል፦ {region}',
  'order.selfDeclared': 'ይህንን መለያ እርስዎ ራስዎ አረጋግጠዋል',
  'order.number': 'ትዕዛዝ',
  'order.viewVault': 'በካዝና ውስጥ እይ',
  'order.note.pending': 'ትዕዛዝዎን ተቀብለናል፤ በቅርቡ እንጀምራለን።',
  'order.note.processing': 'ትዕዛዝዎን አሁን እየሠራንበት ነው።',
  'order.note.completedTopup': 'ወደ ጨዋታ መለያዎ ተልኳል።',
  'order.note.completedCode': 'ኮዱ በካዝናዎ ውስጥ ተዘጋጅቷል።',
  'order.note.failed': 'ይህን ትዕዛዝ ማድረስ አልቻልንም። {amount} ወደ ቀሪ ሂሳብዎ ተመልሷል።',
  'order.note.refunded': '{amount} ወደ ቀሪ ሂሳብዎ ተመልሷል።',
  'status.pending': 'በመጠባበቅ ላይ',
  'status.processing': 'በሂደት ላይ',
  'status.completed': 'ተጠናቋል',
  'status.failed': 'አልተሳካም',
  'status.refunded': 'ተመላሽ ተደርጓል',

  'vault.title': 'ካዝና',
  'vault.subtitle': 'የስጦታ ካርድ፣ የጨዋታ ቁልፍ እና የምዝገባ ኮዶች።',
  'vault.emptyTitle': 'ገና ምንም ኮድ የለም',
  'vault.emptyBody':
    'የገዙት የስጦታ ካርድ፣ የጨዋታ ቁልፍ እና የምዝገባ ኮዶች እዚህ ይታያሉ። ዳይመንድና UC በቀጥታ ወደ ጨዋታ መለያዎ ይላካሉ።',
  'vault.reveal': 'አሳይ',
  'vault.hide': 'ደብቅ',
  'vault.used': 'ጥቅም ላይ ውሏል',
  'vault.markUsed': 'እንደዋለ ምልክት አድርግ',
  'vault.unused': 'ለመጠቀም ዝግጁ',
  'vault.paidAmount': 'የተከፈለ {amount}', // draft, needs a native speaker (see AMHARIC_REVIEW.md)

  'profile.title': 'መገለጫ',
  'profile.history': 'ግብይቶች',
  'profile.noHistory': 'ገና ምንም ግብይት የለም።',
  'profile.language': 'ቋንቋ',
  'profile.support': 'ድጋፍ',
  'profile.supportBody': 'ስለ ትዕዛዝ ወይም ሂሳብ መሙላት እርዳታ ይፈልጋሉ?',
  'profile.signOut': 'ውጣ',
  'profile.adminView': 'ወደ አስተዳዳሪ እይታ ቀይር',
  'notif.title': 'ማሳወቂያዎች',
  'notif.empty': 'እስካሁን ምንም ማሳወቂያ የለም',
  'notif.emptyHint': 'ቅናሾች እና የዋሌት ማሻሻያዎች እዚህ ይታያሉ።',
  'notif.unreadRow': 'ያልተነበበ',
  'gift.menu.title': 'ስጦታ',
  'gift.menu.body': 'ለሌላ ሰው ጥቅል ይግዙ። እስኪቀበሉት ድረስ በካዝናቸው ውስጥ ይጠብቃል።',
  'gift.send.title': 'ለጓደኛ ይላኩ',
  'gift.send.body': 'በኢሜይል ያግኟቸው። በቀጥታ ወደ ካዝናቸው ይሄዳል።',
  'gift.code.title': 'የመጠቀሚያ ኮድ ይፍጠሩ',
  'gift.code.body': 'ለማንም ሰው የሚሰጡት ኮድ ያግኙ።',
  'gift.email.label': 'የጓደኛዎ ጂሜይል',
  'gift.email.placeholder': 'name@gmail.com',
  'gift.email.find': 'ፈልግ',
  'gift.email.invalid': 'ሙሉ የኢሜይል አድራሻቸውን ያስገቡ።',
  'gift.email.notFound': 'ይህን ኢሜይል የሚጠቀም የPortal መለያ የለም። ያረጋግጡና እንደገና ይሞክሩ።',
  'gift.email.self': 'ይህ የራስዎ መለያ ነው። ለራስዎ ስጦታ መላክ አይችሉም።',
  'gift.email.tooMany': 'በጣም ብዙ ፍለጋዎች። ጥቂት ደቂቃዎች ቆይተው እንደገና ይሞክሩ።',
  'gift.email.error': 'አሁን መፈለግ አልተቻለም። እንደገና ይሞክሩ።',
  'gift.confirm.title': 'ስጦታዎ የሚሄደው ለ',
  'gift.confirm.choose': 'ለ{name} ጥቅል ይምረጡ',
  'gift.confirm.change': 'እሳቸው አይደሉም? ኢሜይሉን ይቀይሩ',
  'gift.banner.gift': 'ስጦታ ለ{name}',
  'gift.banner.code': 'የመጠቀሚያ ኮድ እየገዙ ነው',
  'gift.banner.hint': 'አሁን የተጫዋች መለያ አያስፈልግም፤ ስጦታው ሲወሰድ ይጠየቃል።',
  'gift.banner.cancel': 'ስጦታውን ሰርዝ',
  'gift.buy.gift': 'ይህን ጥቅል በስጦታ ላክ',
  'gift.buy.code': 'የመጠቀሚያ ኮድ ግዛ',
  'gift.error.pack': 'ይህ ጥቅል ከአሁን በኋላ አይገኝም። ሌላ ይምረጡ።',
  'gift.error.pending': 'ያልተከፈለ ትዕዛዝ አለዎት። መጀመሪያ ይጨርሱት ወይም ይሰርዙት።',
  'gift.error.other': 'ስጦታውን መግዛት አልተቻለም። እንደገና ይሞክሩ።',
  'gift.done.giftTitle': 'ስጦታው ተልኳል',
  'gift.done.giftBody': '{pack} በ{name} ካዝና ውስጥ እየጠበቀ ነው። እዚያው ይቀበሉታል።',
  'gift.done.codeTitle': 'የመጠቀሚያ ኮድዎ',
  'gift.done.codeBody': 'ለ{pack}። አሁን ይቅዱትና ለማንም ይላኩ።',
  'gift.done.codeUse': 'ይህ ኮድ ያለው ማንኛውም ሰው በመገለጫ → ኮድ ተጠቀም ውስጥ ሊጠቀምበት ይችላል። በካዝናዎ ውስጥም ያገኙታል።',
  'gift.done.codeSecret': 'እንደ ጥሬ ገንዘብ ይያዙት፤ ያየው ሰው ሊጠቀምበት ይችላል።',
  'gift.done.copy': 'ኮዱን ቅዳ',
  'gift.done.expires': 'ያልተጠቀሙባቸው ኮዶችና ስጦታዎች ከ90 ቀናት በኋላ ጊዜያቸው ያልፋል።',
  'gift.done.done': 'ተጠናቋል',
  'gift.done.waiting': 'ክፍያዎ እስኪረጋገጥ እየጠበቅን ነው…',
  'vault.filter.all': 'ሁሉም',
  'vault.filter.cards': 'የስጦታ ካርዶች',
  'vault.filter.gifts': 'ስጦታዎች',
  'vault.filter.codes': 'የመጠቀሚያ ኮዶች',
  'vault.emptyGifts': 'እስካሁን ስጦታ የለም። አንድ ሰው ሲልክልዎ እዚህ እስኪወስዱት ይጠብቃል።',
  'vault.emptyCodes': 'እስካሁን የመጠቀሚያ ኮድ የለም። በመገለጫ → ስጦታ ውስጥ ይግዙ።',
  'vault.gift.badge': 'ስጦታ',
  'vault.gift.from': 'ከ{name}',
  'vault.gift.fromCode': 'ከመጠቀሚያ ኮድ',
  'vault.gift.claimWithin': 'በ{n} ቀናት ውስጥ ይውሰዱ',
  'vault.gift.claimToday': 'ዛሬ ይውሰዱ፤ ጊዜው ሊያልፍ ነው',
  'vault.gift.claim': 'ስጦታውን ውሰድ',
  'vault.gift.claimed': 'ተወስዷል',
  'vault.gift.expired': 'ጊዜው አልፏል',
  'vault.gift.delivering': 'ተወስዷል፣ እየደረሰ ነው',
  'vault.gift.delivered': 'ተወስዶ ደርሷል',
  'vault.gift.view': 'አቅርቦቱን ይመልከቱ',
  'vault.gift.deliveredToast': 'ስጦታው ተወስዶ ደርሷል',
  'vault.gift.queued': 'ተወስዷል! አቅርቦቱ ወዲያው አልተጠናቀቀም። ተሰልፏል፤ ቡድናችን ያጠናቅቅልዎታል።',
  'vault.gift.regionWrong': 'ይህ ጥቅል ለመለያዎ ክልል ({region}) አይደለም።',
  'vault.claimErr.gift_already_claimed': 'ይህ ስጦታ አስቀድሞ ተወስዷል።',
  'vault.claimErr.gift_expired': 'የዚህ ስጦታ ጊዜ አልፏል።',
  'vault.claimErr.gift_not_yours': 'ይህ ስጦታ ለሌላ መለያ ነው የተላከው።',
  'vault.claimErr.gift_not_found': 'ይህ ስጦታ ከአሁን በኋላ የለም።',
  'vault.claimErr.pack_unavailable': 'ይህ ጥቅል አሁን አይገኝም። ቆይተው ይሞክሩ።',
  'vault.claimErr.player_id_required': 'መጀመሪያ የተጫዋች መለያዎን ያስገቡ።',
  'vault.claimErr.id_fields_invalid': 'ያ መለያ ትክክል አይመስልም። ያረጋግጡና እንደገና ይሞክሩ።',
  'vault.claimErr.id_not_validated': 'መለያዎ እስኪረጋገጥ ይጠብቁ፣ ከዚያ ይውሰዱ።',
  'vault.claimErr.id_validation_expired': 'የመለያ ማረጋገጫዎ ጊዜ አልፏል። እንደገና ያረጋግጡና ይውሰዱ።',
  'vault.claimErr.region_unverifiable': 'የመለያዎ ክልል ለዚህ ጥቅል ሊረጋገጥ አይችልም።',
  'vault.claimErr.region_unverified': 'የመለያዎ ክልል ሊረጋገጥ ስላልቻለ ይህ ጥቅል ሊላክለት አይችልም።',
  'vault.claimErr.region_mismatch': 'ይህ ጥቅል ለመለያዎ ክልል አይደለም።',
  'vault.claimErr.not_authenticated': 'ለመውሰድ እንደገና ይግቡ።',
  'vault.claimErr.unknown': 'አሁን መውሰድ አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'vault.code.active': 'ገና ጥቅም ላይ አልዋለም',
  'vault.code.redeemed': 'ጥቅም ላይ ውሏል',
  'vault.code.expired': 'ጊዜው አልፏል',
  'vault.code.hint': 'ማንኛውም ሰው በመገለጫ → ኮድ ተጠቀም ውስጥ ሊጠቀምበት ይችላል።',
  'notif.giftReceived.title': 'ስጦታ ደርሶዎታል',
  'notif.giftReceived.body': '{name} {product} {pack} ልኮልዎታል። በካዝናዎ ውስጥ ይቀበሉት።',
  'notif.giftClaimed.title': 'ስጦታዎ ተወስዷል',
  'notif.giftClaimed.body': '{name} የላኩትን {product} {pack} ወስደዋል።',
  'notif.codeRedeemed.title': 'የመጠቀሚያ ኮድዎ ጥቅም ላይ ውሏል',
  'notif.codeRedeemed.body': 'የ{product} {pack} ኮድዎ ጥቅም ላይ ውሏል።',
  'notif.giftDelivered.title': 'ስጦታዎ ደርሷል',
  'notif.giftDelivered.body': '{product} {pack} ደርሷል።',
  'notif.opens.vault': 'ካዝናዎን ይከፍታል',
  'notif.opens.receipt': 'ደረሰኝዎን ይከፍታል',
  'notif.tournamentTeam.title': 'አዲስ ቡድን ተመዝግቧል',
  'notif.tournamentTeam.body': '{team} ለ{tournament} ተመዝግቧል ({n} ከ{total} ቡድኖች)።',
  'notif.tournamentJoined.title': 'የውድድር ቡድን አባል ሆነዋል',
  'notif.tournamentJoined.body': '{name} ለ{tournament} በ{team} ቡድን ውስጥ አስገብቶዎታል።',
  'notif.tournamentStarting.title': 'ውድድሩ ሊጀምር ነው',
  'notif.tournamentStarting.body': '{tournament} በጥቂት ደቂቃዎች ውስጥ ይጀምራል። ይዘጋጁ!',
  'notif.tournamentCancelled.title': 'ውድድሩ ተሰርዟል',
  'notif.tournamentCancelled.body': '{tournament} was cancelled. Any entry fee you paid is back in your wallet.',
  'notif.opens.tournament': 'ውድድሩን ይከፍታል',
  'notif.tournamentRefunded.title': 'ምዝገባው አልተሳካም',
  'notif.tournamentRefunded.body': '{tournament}: the payment is back in your wallet.',
  'tx.tournament': 'ውድድር',
  'order.gift.title': 'የተቀበሉት ስጦታ',
  'order.gift.from': 'ለእርስዎ የተሰጠ ስጦታ',
  'order.gift.deliveredTo': 'የደረሰበት',
  'order.gift.noReceipt': 'Nothing was charged to you. The receipt stays with the person who bought it.',
  'order.gift.buyerGift': 'ስጦታው ተልኳል። እስኪቀበሉት ድረስ በካዝናቸው ውስጥ ይጠብቃል።',
  'order.gift.buyerCode': 'የመጠቀሚያ ኮድዎ በካዝናዎ ውስጥ ነው። ሊያገኘው ለሚገባ ሰው ያጋሩት።',
  'gift.done.receipt': 'ደረሰኝ ይመልከቱ',
  'gift.choice.title': 'ሰርቨሩን ይምረጡ',
  'gift.choice.hintGift': 'ለእነሱ ይምረጡ። ሲቀበሉት የተጫዋች መለያቸውን ብቻ ይጽፋሉ።',
  'gift.choice.hintCode': 'አሁን ይምረጡ። ኮዱን የሚጠቀም ሰው የተጫዋች መለያውን ብቻ ይጽፋል።',
  'gift.error.choice': 'መጀመሪያ ሰርቨሩን ይምረጡ።',
  'vault.gift.chosen': '{label}: {value}',
  'redeem.title': 'ኮድ ተጠቀም',
  'redeem.body': 'ከአንድ ሰው ኮድ አግኝተዋል? ስጦታውን ወደ ካዝናዎ ለመጨመር ያስገቡት።',
  'redeem.label': 'ኮድ',
  'redeem.placeholder': 'ABCDE FGHIJ',
  'redeem.paste': 'ለጥፍ',
  'redeem.submit': 'ተጠቀም',
  'redeem.short': 'ኮድ 10 ፊደሎችና ቁጥሮች አሉት።',
  'redeem.err.invalid': 'That code doesn\'t work. Check each character and try again.',
  'redeem.err.mine': 'You\'ve already redeemed this code. It\'s in your Vault.',
  'redeem.err.tooMany': 'Too many tries. Wait 10 minutes, then try again.',
  'redeem.err.error': 'Couldn\'t check the code right now. Check your connection and try again.',
  'redeem.done.title': 'ወደ ካዝናዎ ታክሏል',
  'redeem.done.body': 'Claim it now, or later from your Vault.',
  'redeem.openVault': 'ካዝናን ክፈት',
  'redeem.another': 'ሌላ ኮድ ተጠቀም',
  'gift.terms.title': 'ከመግዛትዎ በፊት',
  'gift.terms.noRefund': 'Gifts and redeem codes can\'t be refunded. Unused ones expire after 90 days.',
  'gift.terms.regionGift': 'This pack only works for game accounts in {regions}. Make sure theirs is in that region: an account elsewhere can\'t claim it.',
  'gift.terms.regionCode': 'This pack only works for game accounts in {regions}. Whoever redeems the code needs an account in that region.',
  'gift.confirm.titleGift': 'ይህን ስጦታ ይገዛሉ?',
  'gift.confirm.titleCode': 'ይህን የመጠቀሚያ ኮድ ይገዛሉ?',
  'gift.confirm.bodyGift': '{pack} for {name}, {price}. Gifts can\'t be refunded.',
  'gift.confirm.bodyCode': '{pack} as a redeem code, {price}. Redeem codes can\'t be refunded.',
  'gift.confirm.buy': 'ግዛ',
  'orders.gift.sent': 'ስጦታ ተልኳል',
  'orders.gift.code': 'የመጠቀሚያ ኮድ',
  'orders.gift.received': 'የተቀበሉት ስጦታ',
  'orders.gift.state.pending': 'እስኪወሰድ እየጠበቀ',
  'orders.gift.state.claimed': 'ተወስዷል',
  'orders.gift.state.expired': 'ጊዜው አልፏል',
  'orders.gift.state.active': 'ገና አልተወሰደም',
  'orders.gift.state.redeemed': 'ተወስዷል',
  'pay.viewGift': 'ስጦታዎን ይመልከቱ',
  'notif.bellUnread': 'ማሳወቂያዎች፣ {n} ያልተነበቡ',
  'notif.now': 'አሁን',
  'notif.minutes': '{n} ደቂቃ',
  'notif.hours': '{n} ሰዓት',
  'notif.days': '{n} ቀን',
  'notif.discount.title': 'ቅናሽ ተደርጓል',
  'notif.discount.body': '{product} {pack} አሁን {percent}% ቅናሽ',
  'notif.deposit.title': 'ተቀማጭ ጸድቋል',
  'notif.deposit.body': '{amount} ወደ ዋሌትዎ ገብቷል',
  'notif.refund.title': 'ገንዘብ ተመልሷል',
  'notif.refund.body': '{amount} ወደ ዋሌትዎ ተመልሷል',
  'notif.commission.title': 'ኮሚሽን ተገኝቷል',
  'notif.commission.body': '{amount} ከኮድ {code}',
  'notif.commissionNoCode.body': '{amount} ኮሚሽን ወደ ዋሌትዎ ገብቷል',
  'notif.withdrawal.title': 'ገንዘብ ተልኳል',
  'notif.withdrawal.body': '{amount} ተልኮልዎታል',
  'notif.opens.discountPack': '{product}ን ይከፍታል፣ ቅናሽ የተደረገበትን ጥቅል',
  'notif.opens.product': '{product}ን ይከፍታል',
  'notif.opens.deposit': 'ገቢዎን በግብይቶች ውስጥ ይከፍታል',
  'notif.opens.refund': 'ተመላሽዎን በግብይቶች ውስጥ ይከፍታል',
  'notif.opens.commission': 'ኮሚሽንዎን በግብይቶች ውስጥ ይከፍታል',
  'notif.opens.withdrawal': 'ወጪዎን በግብይቶች ውስጥ ይከፍታል',
  'accounts.add': 'መለያ ያክሉ',
  'accounts.active': 'ንቁ',
  'accounts.removeHint': 'ከዚህ መሣሪያ ለማስወገድ ተጭነው ይያዙ',
  'accounts.limitHint': '3 ከ3 · ለማስወገድ አንድ መለያ ተጭነው ይያዙ',
  'accounts.limitBody': 'በዚህ መሣሪያ ላይ እስከ 3 መለያዎች መያዝ ይችላሉ። አንዱን ተጭነው ይዘው ያስወግዱ፣ ከዚያ አዲሱን ያክሉ።',
  'accounts.removeTitle': 'ከዚህ መሣሪያ ይወገድ?',
  'accounts.removeBody': 'ይህ {name}ን ከዚህ መሣሪያ ብቻ ያስወግዳል። መለያው አይሰረዝም፣ በሌላ ቦታም አይወጣም።',
  'accounts.removeActiveBody': 'አሁን {name}ን እየተጠቀሙ ነው። ማስወገድ በዚህ መሣሪያ ላይ ብቻ ያስወጣዋል፤ መለያው አይሰረዝም፣ በሌላ ቦታም አይወጣም።',
  'accounts.remove': 'አስወግድ',
  'accounts.expiredTitle': 'እንደገና ይግቡ',
  'accounts.expiredBody': '{name} በዚህ መሣሪያ ላይ ከአሁን በኋላ አልገባም። እዚህ መጠቀሙን ለመቀጠል እንደገና ይግቡ።',
  'accounts.signInAgain': 'እንደገና ይግቡ',
  'accounts.needsSignIn': 'ወጥቷል · ለመግባት ይንኩ',
  'accounts.switchFailed': 'መለያ መቀየር አልተቻለም። እንደገና ይሞክሩ።',
  'settings.title': 'ቅንብሮች',
  'settings.editProfile': 'መገለጫ አስተካክል',
  'settings.account': 'መለያ',
  'settings.privacy': 'ግላዊነት',
  'editProfile.changePhoto': 'ፎቶ ቀይር',
  'editProfile.name': 'የሚታይ ስም',
  'editProfile.save': 'አስቀምጥ',
  'editProfile.saved': 'መገለጫ ተቀምጧል',
  'editProfile.nameInvalid': 'ከ2 እስከ 40 ፊደላት ይጠቀሙ።',
  'editProfile.photoSaved': 'ፎቶ ተቀይሯል',
  'editProfile.photoFailed': 'ፎቶዎን መቀየር አልተቻለም። እንደገና ይሞክሩ።',
  'account.google': 'Google',
  'account.emailPassword': 'ኢሜይልና የይለፍ ቃል',
  'account.changePassword': 'የይለፍ ቃል ቀይር',
  'account.currentPassword': 'የአሁኑ የይለፍ ቃል',
  'account.newPassword': 'አዲስ የይለፍ ቃል',
  'account.wrongPassword': 'የአሁኑ የይለፍ ቃልዎ የተሳሳተ ነው።',
  'account.samePassword': 'ከአሁኑ የተለየ የይለፍ ቃል ይምረጡ።',
  'account.passwordChanged': 'የይለፍ ቃል ተቀይሯል',
  'account.passwordFailed': 'የይለፍ ቃልዎን መቀየር አልተቻለም። እንደገና ይሞክሩ።',
  'account.sectionSignIn': 'መግቢያ',
  'account.sectionSecurity': 'ደህንነት',
  'account.connected': 'ተገናኝቷል',
  'account.passwordSet': 'ተዘጋጅቷል',
  'account.passwordNotSet': 'አልተዘጋጀም',
  'account.addPassword': 'የይለፍ ቃል ያክሉ',
  'account.addPasswordBody': 'በGoogle ብቻ ሳይሆን በኢሜይልዎም መግባት እንዲችሉ የይለፍ ቃል ያክሉ።',
  'account.confirmPassword': 'አዲሱን የይለፍ ቃል ያረጋግጡ',
  'account.mismatch': 'ሁለቱ የይለፍ ቃሎች አይመሳሰሉም።',
  'account.passwordAdded': 'የይለፍ ቃል ታክሏል',
  'account.network': 'ግንኙነት የለም። ኢንተርኔትዎን ያረጋግጡና እንደገና ይሞክሩ።',
  'privacy.policy': 'የግላዊነት ፖሊሲ',
  'privacy.deleteAccount': 'መለያ እንዲሰረዝ ይጠይቁ',
  'privacy.deleteBody': 'መለያዎና መረጃዎ እንዲሰረዝ ድጋፍን ያግኙና ይጠይቁ። እያንዳንዱን ጥያቄ በእጅ እናስተናግዳለን።',
  'tx.deposit': 'ገቢ',
  'tx.purchase': 'ግዢ',
  'tx.refund': 'ተመላሽ',
  'tx.adjustment': 'ማስተካከያ',

  'topup.title': 'ሂሳብ ሙላ',
  'topup.body': 'ክፍያዎን ይላኩና ይጻፉልን። ክፍያውን እንዳረጋገጥን ገንዘቡን ወደ ቀሪ ሂሳብዎ እንጨምራለን።',
  'topup.noContact': 'ወደ ሂሳብዎ ገንዘብ እንዲጨመርልዎ ሱቁን ይጠይቁ።',
  'topup.account': 'የእርስዎ መለያ',
  'topup.contact': 'ድጋፍን አግኙ',
  // English placeholders first, then the Amharic that exists (AM_CART_WALLET) overrides them. See AM_NEEDS_REVIEW.
  ...CART_STRINGS,
  ...WALLET_STRINGS,
  ...AUTH_STRINGS_AM,
  ...UI_STRINGS_AM,
  ...WHEEL_STRINGS_AM,
  ...HEADER_STRINGS_AM,
  ...AM_CART_WALLET,
  ...TOURNAMENT_STRINGS_AM,
};
